### ISSUE TITLE
Getting an error after installing mods

### ISSUE THREAD

**Issue by FireFaced** [KSP-CKAN/CKAN#1093]
> ************** Exception Text **************
System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,CKAN.Version> CKAN.Registry.Installed()'.
   at PartManagerPlugin.PartManagerUI.RefreshInstalledModsList()
   at PartManagerPlugin.PartManagerUI.OnModChanged(CkanModule module, GUIModChangeType changeType)
   at CKAN.Main.PostInstallMods(Object sender, RunWorkerCompletedEventArgs e)

I've tried disabling/removing PartManager, but it still remains there.

**Comment by Dazpoet** [comment]
You need to also remove the .dll from the Plugins folder.

**Comment by FireFaced** [comment]
Oh, okay.

**Comment by FireFaced** [comment]
Error is gone.
