### ISSUE TITLE
Stack trace.

### ISSUE THREAD

**Issue by valuial** [KSP-CKAN/CKAN#1207]
I'm not really sure what causes this to happen - I hope it's not my mono, as I only really use ckan with mono (everything else comes with its own bundled mono)... First time something like this happened was when I tried launching ksp from the gui, but this time it was something else (I use a lot of CLI, and usually launch ksp myself). Not entirely sure, as ckan was in the background, but this might have happened during update/install of mods.

```
*** longjmp causes uninitialized stack frame ***: mono terminated
======= Backtrace: =========
/lib64/libc.so.6(+0x72d1f)[0x7f139b5d1d1f]
/lib64/libc.so.6(__fortify_fail+0x37)[0x7f139b656a67]
/lib64/libc.so.6(+0xf799d)[0x7f139b65699d]
/lib64/libc.so.6(__longjmp_chk+0x29)[0x7f139b6568f9]
/usr/lib64/libcurl.so(+0xa915)[0x7f1382176915]
/lib64/libpthread.so.0(+0x10050)[0x7f139b907050]
/lib64/libc.so.6(__poll+0x2d)[0x7f139b63dc8d]
[0x40e0a1e6]
======= Memory map: ========
00400000-00747000 r-xp 00000000 08:12 1869383                            /usr/bin/mono-sgen
00946000-00947000 r--p 00346000 08:12 1869383                            /usr/bin/mono-sgen
00947000-00950000 rw-p 00347000 08:12 1869383                            /usr/bin/mono-sgen
00950000-01c98000 rw-p 00000000 00:00 0                                  [heap]
4088f000-4089f000 rwxp 00000000 00:00 0 
40bcc000-40ed0000 rwxp 00000000 00:00 0 
412d8000-412d9000 r--p 00000000 00:00 0 
41f58000-41f59000 ---p 00000000 00:00 0 
7f135c000000-7f135c291000 rw-p 00000000 00:00 0 
7f135c291000-7f1360000000 ---p 00000000 00:00 0 
7f1360000000-7f1360133000 rw-p 00000000 00:00 0 
7f1360133000-7f1364000000 ---p 00000000 00:00 0 
7f1364000000-7f1364021000 rw-p 00000000 00:00 0 
7f1364021000-7f1368000000 ---p 00000000 00:00 0 
7f1368000000-7f136802d000 rw-p 00000000 00:00 0 
7f136802d000-7f136c000000 ---p 00000000 00:00 0 
7f136c000000-7f136c021000 rw-p 00000000 00:00 0 
7f136c021000-7f1370000000 ---p 00000000 00:00 0 
7f1371dc2000-7f1371f69000 r-xp 00000000 08:12 1716112                    /usr/lib64/libcrypto.so.1.0.0
7f1371f69000-7f1372169000 ---p 001a7000 08:12 1716112                    /usr/lib64/libcrypto.so.1.0.0
7f1372169000-7f1372183000 r--p 001a7000 08:12 1716112                    /usr/lib64/libcrypto.so.1.0.0
7f1372183000-7f137218e000 rw-p 001c1000 08:12 1716112                    /usr/lib64/libcrypto.so.1.0.0
7f137218e000-7f1372192000 rw-p 00000000 00:00 0 
7f1372192000-7f13721f3000 r-xp 00000000 08:12 1743645                    /usr/lib64/libssl.so.1.0.0
7f13721f3000-7f13723f2000 ---p 00061000 08:12 1743645                    /usr/lib64/libssl.so.1.0.0
7f13723f2000-7f13723f6000 r--p 00060000 08:12 1743645                    /usr/lib64/libssl.so.1.0.0
7f13723f6000-7f13723fd000 rw-p 00064000 08:12 1743645                    /usr/lib64/libssl.so.1.0.0
7f1372865000-7f1372866000 ---p 00000000 00:00 0 
7f1372866000-7f1372a66000 rw-p 00000000 00:00 0 
7f1373429000-7f137343e000 r-xp 00000000 08:12 1842824                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f137343e000-7f137363d000 ---p 00015000 08:12 1842824                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f137363d000-7f137363e000 r--p 00014000 08:12 1842824                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f137363e000-7f137363f000 rw-p 00015000 08:12 1842824                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.4/libgcc_s.so.1
7f1374000000-7f13741b0000 rw-p 00000000 00:00 0 
7f13741b0000-7f1378000000 ---p 00000000 00:00 0 
7f1378000000-7f1378101000 rw-p 00000000 00:00 0 
7f1378101000-7f137c000000 ---p 00000000 00:00 0 
7f137c000000-7f137c021000 rw-p 00000000 00:00 0 
7f137c021000-7f1380000000 ---p 00000000 00:00 0 
7f13800a5000-7f13800b3000 r-xp 00000000 08:12 1718064                    /usr/lib64/liblber-2.4.so.2.10.1
7f13800b3000-7f13802b2000 ---p 0000e000 08:12 1718064                    /usr/lib64/liblber-2.4.so.2.10.1
7f13802b2000-7f13802b3000 r--p 0000d000 08:12 1718064                    /usr/lib64/liblber-2.4.so.2.10.1
7f13802b3000-7f13802b4000 rw-p 0000e000 08:12 1718064                    /usr/lib64/liblber-2.4.so.2.10.1
7f13802b4000-7f13802ec000 rw-p 00000000 00:00 0 
7f13802f0000-7f13802f8000 rw-p 00000000 00:00 0 
7f1380310000-7f1380334000 rw-p 00000000 00:00 0 
7f1380338000-7f13803b8000 rw-p 00000000 00:00 0 
7f13803bc000-7f138043c000 rw-p 00000000 00:00 0 
7f1380440000-7f13804a4000 rw-p 00000000 00:00 0 
7f13804ac000-7f13804c0000 rw-p 00000000 00:00 0 
7f13804c4000-7f13804d8000 rw-p 00000000 00:00 0 
7f13804e0000-7f1380504000 rw-p 00000000 00:00 0 
7f138050c000-7f1380530000 rw-p 00000000 00:00 0 
7f1380538000-7f1380544000 rw-p 00000000 00:00 0 
7f1380548000-7f138055c000 rw-p 00000000 00:00 0 
7f1380560000-7f1380574000 rw-p 00000000 00:00 0 
7f1380578000-7f1380590000 rw-p 00000000 00:00 0 
7f1380594000-7f138059c000 rw-p 00000000 00:00 0 
7f13805a0000-7f13805b4000 rw-p 00000000 00:00 0 
7f13805b8000-7f13805c8000 rw-p 00000000 00:00 0 
7f13805cc000-7f13805d4000 rw-p 00000000 00:00 0 
7f13805d8000-7f13805ec000 rw-p 00000000 00:00 0 
7f13805f0000-7f13805f4000 rw-p 00000000 00:00 0 
7f13805f8000-7f1380618000 rw-p 00000000 00:00 0 
7f138061c000-7f1380628000 rw-p 00000000 00:00 0 
7f138062c000-7f1380634000 rw-p 00000000 00:00 0 
7f1380638000-7f138064c000 rw-p 00000000 00:00 0 
7f1380650000-7f1380660000 rw-p 00000000 00:00 0 
7f1380664000-7f1380668000 rw-p 00000000 00:00 0 
7f138066c000-7f1380684000 rw-p 00000000 00:00 0 
7f1380688000-7f1380694000 rw-p 00000000 00:00 0 
7f1380698000-7f13806b8000 rw-p 00000000 00:00 0 
7f13806bc000-7f13806c0000 rw-p 00000000 00:00 0 
7f13806c4000-7f13806d0000 rw-p 00000000 00:00 0 
7f13806d4000-7f13806e0000 rw-p 00000000 00:00 0 
7f13806e4000-7f13806e8000 rw-p 00000000 00:00 0 
7f13806f4000-7f13806fc000 rw-p 00000000 00:00 0 
7f1380704000-7f1380708000 rw-p 00000000 00:00 0 
7f138070c000-7f1380714000 rw-p 00000000 00:00 0 
7f138071c000-7f1380720000 rw-p 00000000 00:00 0 
7f1380790000-7f1380794000 rw-p 00000000 00:00 0 
7f13807e8000-7f13807ec000 rw-p 00000000 00:00 0 
7f1380904000-7f138090c000 rw-p 00000000 00:00 0 
7f1380914000-7f1380918000 rw-p 00000000 00:00 0 
7f138091c000-7f1380920000 rw-p 00000000 00:00 0 
7f1380938000-7f138093c000 rw-p 00000000 00:00 0 
7f138096c000-7f1380970000 rw-p 00000000 00:00 0 
7f13809a4000-7f13809a8000 rw-p 00000000 00:00 0 
7f13809d8000-7f13809dc000 rw-p 00000000 00:00 0 
7f13809e0000-7f13809e4000 rw-p 00000000 00:00 0 
7f13809f4000-7f13809f8000 rw-p 00000000 00:00 0 
7f1380a18000-7f1380a1c000 rw-p 00000000 00:00 0 
7f1380a48000-7f1380a4c000 rw-p 00000000 00:00 0 
7f1380a78000-7f1380a7c000 rw-p 00000000 00:00 0 
7f1380b54000-7f1380b58000 rw-p 00000000 00:00 0 
7f1380c8c000-7f1380c90000 rw-p 00000000 00:00 0 
7f1380cf4000-7f1380cf8000 rw-p 00000000 00:00 0 
7f1380d34000-7f1380d38000 rw-p 00000000 00:00 0 
7f1380d74000-7f1380d78000 rw-p 00000000 00:00 0 
7f1380ef4000-7f1380ef8000 rw-p 00000000 00:00 0 
7f1380f04000-7f1380f10000 rw-p 00000000 00:00 0 
7f1380f14000-7f1380f28000 rw-p 00000000 00:00 0 
7f1380f2c000-7f1380f94000 rw-p 00000000 00:00 0 
7f1380f98000-7f1380fec000 rw-p 00000000 00:00 0 
7f1380ff0000-7f1381018000 rw-p 00000000 00:00 0 
7f138101c000-7f1381090000 rw-p 00000000 00:00 0 
7f1381094000-7f138109c000 rw-p 00000000 00:00 0 
7f13810a0000-7f13810bc000 rw-p 00000000 00:00 0 
7f13810c0000-7f13810d0000 rw-p 00000000 00:00 0 
7f13810d4000-7f13810e8000 rw-p 00000000 00:00 0 
7f13810ec000-7f13810f4000 rw-p 00000000 00:00 0 
7f13810f8000-7f1381104000 rw-p 00000000 00:00 0 
7f1381108000-7f1381114000 rw-p 00000000 00:00 0 
7f1381118000-7f1381120000 rw-p 00000000 00:00 0 
7f1381128000-7f1381130000 rw-p 00000000 00:00 0 
7f1381134000-7f1381140000 rw-p 00000000 00:00 0 
7f1381144000-7f1381158000 rw-p 00000000 00:00 0 
7f138115c000-7f1381178000 rw-p 00000000 00:00 0 
7f1381180000-7f138118c000 rw-p 00000000 00:00 0 
7f1381194000-7f13811a0000 rw-p 00000000 00:00 0 
7f13811a8000-7f13811b0000 rw-p 00000000 00:00 0 
7f13811c4000-7f1381228000 rw-p 00000000 00:00 0 
7f138122c000-7f1381264000 rw-p 00000000 00:00 0 
7f1381268000-7f1381270000 rw-p 00000000 00:00 0 
7f1381274000-7f1381278000 rw-p 00000000 00:00 0 
7f138127c000-7f1381280000 rw-p 00000000 00:00 0 
7f13812a8000-7f13812ac000 rw-p 00000000 00:00 0 
7f13812cc000-7f13812d0000 rw-p 00000000 00:00 0 
7f138130f000-7f1381356000 r-xp 00000000 08:12 1718062                    /usr/lib64/libldap-2.4.so.2.10.1
7f1381356000-7f1381555000 ---p 00047000 08:12 1718062                    /usr/lib64/libldap-2.4.so.2.10.1
7f1381555000-7f1381556000 r--p 00046000 08:12 1718062                    /usr/lib64/libldap-2.4.so.2.10.1
7f1381556000-7f1381558000 rw-p 00047000 08:12 1718062                    /usr/lib64/libldap-2.4.so.2.10.1
7f1381558000-7f138155c000 rw-p 00000000 00:00 0 
7f13815ac000-7f13815b4000 rw-p 00000000 00:00 0 
7f13815c8000-7f13815cc000 rw-p 00000000 00:00 0 
7f13815e0000-7f13815e4000 rw-p 00000000 00:00 0 
7f1381600000-7f1381604000 rw-p 00000000 00:00 0 
7f1381718000-7f138171c000 rw-p 00000000 00:00 0 
7f13817c4000-7f13817c8000 rw-p 00000000 00:00 0 
7f138188c000-7f1381898000 rw-p 00000000 00:00 0 
7f13818b4000-7f13818b8000 rw-p 00000000 00:00 0 
7f13818de000-7f138195e000 rw-s 00000000 00:05 19333160                   /SYSV00000000 (deleted)
7f138195e000-7f1381967000 ---p 00000000 00:00 0 
7f1381967000-7f1381b5f000 rw-p 00000000 00:00 0                          [stack:28404]
7f1381ba4000-7f1381ba8000 rw-p 00000000 00:00 0 
7f1381bb0000-7f1381bb4000 rw-p 00000000 00:00 0 
7f1381be8000-7f1381bec000 rw-p 00000000 00:00 0 
7f1381c2c000-7f1381c30000 rw-p 00000000 00:00 0 
7f1381c4c000-7f1381c50000 rw-p 00000000 00:00 0 
7f1381c54000-7f1381c58000 rw-p 00000000 00:00 0 
7f1381c64000-7f1381c68000 rw-p 00000000 00:00 0 
7f1381c73000-7f1381c74000 ---p 00000000 00:00 0 
7f1381c74000-7f1381e78000 rw-p 00000000 00:00 0 
7f1382074000-7f138207c000 rw-p 00000000 00:00 0 
7f13820ac000-7f13820b0000 rw-p 00000000 00:00 0 
7f13820c0000-7f13820c4000 rw-p 00000000 00:00 0 
7f13820cc000-7f13820d0000 rw-p 00000000 00:00 0 
7f13820d8000-7f13820dc000 rw-p 00000000 00:00 0 
7f13820e8000-7f13820f0000 rw-p 00000000 00:00 0 
7f13820f8000-7f13820fc000 rw-p 00000000 00:00 0 
7f1382100000-7f1382104000 rw-p 00000000 00:00 0 
7f138210c000-7f1382110000 rw-p 00000000 00:00 0 
7f138212c000-7f1382130000 rw-p 00000000 00:00 0 
7f138216c000-7f13821cc000 r-xp 00000000 08:12 1718160                    /usr/lib64/libcurl.so.4.3.0
7f13821cc000-7f13823cc000 ---p 00060000 08:12 1718160                    /usr/lib64/libcurl.so.4.3.0
7f13823cc000-7f13823ce000 r--p 00060000 08:12 1718160                    /usr/lib64/libcurl.so.4.3.0
7f13823ce000-7f13823cf000 rw-p 00062000 08:12 1718160                    /usr/lib64/libcurl.so.4.3.0
7f13823cf000-7f13823d8000 ---p 00000000 00:00 0 
7f13823d8000-7f13825d0000 rw-p 00000000 00:00 0                          [stack:28432]
7f13825f8000-7f1382600000 rw-p 00000000 00:00 0 
7f1382610000-7f1382614000 rw-p 00000000 00:00 0 
7f1382638000-7f1382640000 rw-p 00000000 00:00 0 
7f1382644000-7f1382648000 rw-p 00000000 00:00 0 
7f13826c0000-7f13826c4000 rw-p 00000000 00:00 0 
7f1382759000-7f138275e000 r-xp 00000000 08:11 477                        /lib64/libnss_dns-2.20.so
7f138275e000-7f138295d000 ---p 00005000 08:11 477                        /lib64/libnss_dns-2.20.so
7f138295d000-7f138295e000 r--p 00004000 08:11 477                        /lib64/libnss_dns-2.20.so
7f138295e000-7f138295f000 rw-p 00005000 08:11 477                        /lib64/libnss_dns-2.20.so
7f138295f000-7f1382968000 ---p 00000000 00:00 0 
7f1382968000-7f1382be0000 rw-p 00000000 00:00 0                          [stack:28427]
7f1382be4000-7f1382c5c000 rw-p 00000000 00:00 0 
7f1382c60000-7f1382c64000 rw-p 00000000 00:00 0 
7f1382cc3000-7f1382d02000 r-xp 00000000 08:12 1742668                    /usr/lib64/libMonoPosixHelper.so
7f1382d02000-7f1382f01000 ---p 0003f000 08:12 1742668                    /usr/lib64/libMonoPosixHelper.so
7f1382f01000-7f1382f02000 r--p 0003e000 08:12 1742668                    /usr/lib64/libMonoPosixHelper.so
7f1382f02000-7f1382f03000 rw-p 0003f000 08:12 1742668                    /usr/lib64/libMonoPosixHelper.so
7f1382f03000-7f1382f04000 rw-p 00000000 00:00 0 
7f1382f40000-7f1382f84000 rw-p 00000000 00:00 0 
7f1382f88000-7f1382fc8000 rw-p 00000000 00:00 0 
7f1382fcc000-7f1383008000 rw-p 00000000 00:00 0 
7f138300a000-7f13830b4000 r--p 00000000 08:12 1334856                    /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf
7f13830b4000-7f13830e8000 rw-p 00000000 00:00 0 
7f13830ec000-7f1383104000 rw-p 00000000 00:00 0 
7f138310c000-7f138312c000 rw-p 00000000 00:00 0 
7f1383130000-7f1383134000 rw-p 00000000 00:00 0 
7f1383138000-7f138314c000 rw-p 00000000 00:00 0 
7f1383150000-7f1383154000 rw-p 00000000 00:00 0 
7f1383158000-7f138315c000 rw-p 00000000 00:00 0 
7f1383160000-7f1383184000 rw-p 00000000 00:00 0 
7f1383188000-7f138318c000 rw-p 00000000 00:00 0 
7f1383190000-7f13831a0000 rw-p 00000000 00:00 0 
7f13831a4000-7f13831b4000 rw-p 00000000 00:00 0 
7f138322c000-7f138323c000 rw-p 00000000 00:00 0 
7f1383248000-7f138324c000 rw-p 00000000 00:00 0 
7f1383274000-7f1383278000 rw-p 00000000 00:00 0 
7f138345c000-7f1383464000 rw-p 00000000 00:00 0 
7f1383468000-7f1383470000 rw-p 00000000 00:00 0 
7f1383494000-7f1383498000 rw-p 00000000 00:00 0 
7f1383540000-7f1383548000 rw-p 00000000 00:00 0 
7f138354c000-7f1383554000 rw-p 00000000 00:00 0 
7f1383558000-7f1383578000 rw-p 00000000 00:00 0 
7f138357c000-7f1383580000 rw-p 00000000 00:00 0 
7f1383588000-7f138358c000 rw-p 00000000 00:00 0 
7f1383594000-7f13835a8000 rw-p 00000000 00:00 0 
7f13835ac000-7f13835b0000 rw-p 00000000 00:00 0 
7f13835b4000-7f13835bc000 rw-p 00000000 00:00 0 
7f13835c0000-7f13835c8000 rw-p 00000000 00:00 0 
7f13835cc000-7f13835d8000 rw-p 00000000 00:00 0 
7f13835e0000-7f13835e4000 rw-p 00000000 00:00 0 
7f13835e8000-7f13835f4000 rw-p 00000000 00:00 0 
7f13835f8000-7f1383608000 rw-p 00000000 00:00 0 
7f1383610000-7f1383620000 rw-p 00000000 00:00 0 
7f1383624000-7f138362c000 rw-p 00000000 00:00 0 
7f1383630000-7f1383638000 rw-p 00000000 00:00 0 
7f1383644000-7f1383658000 rw-p 00000000 00:00 0 
7f138365c000-7f1383660000 rw-p 00000000 00:00 0 
7f1383664000-7f1383670000 rw-p 00000000 00:00 0 
7f1383674000-7f1383688000 rw-p 00000000 00:00 0 
7f138368c000-7f13836a0000 rw-p 00000000 00:00 0 
7f13836a4000-7f13836ac000 rw-p 00000000 00:00 0 
7f13836b0000-7f13836b4000 rw-p 00000000 00:00 0 
7f13836b8000-7f13836c0000 rw-p 00000000 00:00 0 
7f13836cc000-7f13836e0000 rw-p 00000000 00:00 0 
7f13836e4000-7f13836f0000 rw-p 00000000 00:00 0 
7f13836f4000-7f1383704000 rw-p 00000000 00:00 0 
7f138370c000-7f1383724000 rw-p 00000000 00:00 0 
7f1383728000-7f1383734000 rw-p 00000000 00:00 0 
7f1383738000-7f1383748000 rw-p 00000000 00:00 0 
7f138374c000-7f1383750000 rw-p 00000000 00:00 0 
7f1383754000-7f1383764000 rw-p 00000000 00:00 0 
7f1383768000-7f1383780000 rw-p 00000000 00:00 0 
7f1383784000-7f1383798000 rw-p 00000000 00:00 0 
7f138379c000-7f13837ac000 rw-p 00000000 00:00 0 
7f13837b0000-7f13837cc000 rw-p 00000000 00:00 0 
7f13837d4000-7f13837e0000 rw-p 00000000 00:00 0 
7f13837e4000-7f13837f8000 rw-p 00000000 00:00 0 
7f13837fc000-7f138380c000 rw-p 00000000 00:00 0 
7f1383810000-7f1383820000 rw-p 00000000 00:00 0Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall.sys_poll (Mono.Unix.Native.Syscall/_pollfd[],uint,int) <0xffffffff>
  at Mono.Unix.Native.Syscall.poll (Mono.Unix.Native.Pollfd[],uint,int) <0x000f7>
  at System.Windows.Forms.XplatUIX11.UpdateMessageQueue (System.Windows.Forms.XEventQueue,bool) <0x00403>
  at System.Windows.Forms.XplatUIX11.UpdateMessageQueue (System.Windows.Forms.XEventQueue) <0x00017>
  at System.Windows.Forms.XplatUIX11.GetMessage (object,System.Windows.Forms.MSG&,intptr,int,int) <0x002e3>
  at System.Windows.Forms.XplatUI.GetMessage (object,System.Windows.Forms.MSG&,intptr,int,int) <0x00047>
  at System.Windows.Forms.Application.RunLoop (bool,System.Windows.Forms.ApplicationContext) <0x00e3f>
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext) <0x00073>
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form) <0x00033>
  at CKAN.Main..ctor (string[],CKAN.GUIUser,bool) <0x00c07>
  at (wrapper remoting-invoke-with-check) CKAN.Main..ctor (string[],CKAN.GUIUser,bool) <0xffffffff>
  at CKAN.GUI.Main_ (string[],bool) <0x0010f>
  at CKAN.CmdLine.MainClass.Gui (CKAN.CmdLine.GuiOptions,string[]) <0x00023>
  at CKAN.CmdLine.MainClass.Main (string[]) <0x00167>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

        mono() [0x4b81c8]
        /lib64/libpthread.so.0(+0x10050) [0x7f139b907050]
        /lib64/libc.so.6(gsignal+0x37) [0x7f139b593e77]
        /lib64/libc.so.6(abort+0x16a) [0x7f139b59527a]
        /lib64/libc.so.6(+0x72d24) [0x7f139b5d1d24]
        /lib64/libc.so.6(__fortify_fail+0x37) [0x7f139b656a67]
        /lib64/libc.so.6(+0xf799d) [0x7f139b65699d]
        /lib64/libc.so.6(__longjmp_chk+0x29) [0x7f139b6568f9]
        /usr/lib64/libcurl.so(+0xa915) [0x7f1382176915]
        /lib64/libpthread.so.0(+0x10050) [0x7f139b907050]
        /lib64/libc.so.6(__poll+0x2d) [0x7f139b63dc8d]
        [0x40e0a1e6]

Debug info from gdb:

warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/vee/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/vee/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[New LWP 28432]
[New LWP 28429]
[New LWP 28428]
[New LWP 28427]
[New LWP 28404]
[New LWP 28403]
[New LWP 28393]
[New LWP 28392]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f139b906c39 in waitpid () from /lib64/libpthread.so.0
  Id   Target Id         Frame 
  9    Thread 0x7f1398939700 (LWP 28392) "Finalizer" 0x00007f139b9057f0 in sem_wait () from /lib64/libpthread.so.0
  8    Thread 0x7f13883ff700 (LWP 28393) "Timer-Scheduler" 0x00007f139b90386f in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  7    Thread 0x7f1389473700 (LWP 28403) "Threadpool moni" 0x00007f139b9057f0 in sem_wait () from /lib64/libpthread.so.0
  6    Thread 0x7f1381b5e700 (LWP 28404) "Threadpool work" 0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
  5    Thread 0x7f1382b5f700 (LWP 28427) "Threadpool work" 0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
  4    Thread 0x7f1389273700 (LWP 28428) "Threadpool work" 0x00007f139b646e43 in epoll_wait () from /lib64/libc.so.6
  3    Thread 0x7f1389073700 (LWP 28429) "IO Threadpool w" 0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
  2    Thread 0x7f13825cf700 (LWP 28432) "Threadpool work" 0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
* 1    Thread 0x7f139c413780 (LWP 28391) "mono" 0x00007f139b906c39 in waitpid () from /lib64/libpthread.so.0

Thread 9 (Thread 0x7f1398939700 (LWP 28392)):
#0  0x00007f139b9057f0 in sem_wait () from /lib64/libpthread.so.0
#1  0x0000000000620507 in mono_sem_wait ()
#2  0x00000000005a615e in ?? ()
#3  0x000000000058a906 in ?? ()
#4  0x00000000006251fe in ?? ()
#5  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 8 (Thread 0x7f13883ff700 (LWP 28393)):
#0  0x00007f139b90386f in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000060009b in ?? ()
#2  0x000000000061281b in ?? ()
#3  0x000000000058a28f in ?? ()
#4  0x000000000058b692 in ?? ()
#5  0x0000000040cf54ed in ?? ()
#6  0x0000000000000000 in ?? ()

Thread 7 (Thread 0x7f1389473700 (LWP 28403)):
#0  0x00007f139b9057f0 in sem_wait () from /lib64/libpthread.so.0
#1  0x0000000000620507 in mono_sem_wait ()
#2  0x000000000058d6f2 in ?? ()
#3  0x000000000058a906 in ?? ()
#4  0x00000000006251fe in ?? ()
#5  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f1381b5e700 (LWP 28404)):
#0  0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
#1  0x00000000006205eb in mono_sem_timedwait ()
#2  0x000000000058f5e2 in ?? ()
#3  0x000000000058a906 in ?? ()
#4  0x00000000006251fe in ?? ()
#5  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f1382b5f700 (LWP 28427)):
#0  0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
#1  0x00000000006205eb in mono_sem_timedwait ()
#2  0x000000000058f5e2 in ?? ()
#3  0x000000000058a906 in ?? ()
#4  0x00000000006251fe in ?? ()
#5  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f1389273700 (LWP 28428)):
#0  0x00007f139b646e43 in epoll_wait () from /lib64/libc.so.6
#1  0x000000000058ef02 in ?? ()
#2  0x000000000058a906 in ?? ()
#3  0x00000000006251fe in ?? ()
#4  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f1389073700 (LWP 28429)):
#0  0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
#1  0x00000000006205eb in mono_sem_timedwait ()
#2  0x000000000058f5e2 in ?? ()
#3  0x000000000058a906 in ?? ()
#4  0x00000000006251fe in ?? ()
#5  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f13825cf700 (LWP 28432)):
#0  0x00007f139b9058d0 in sem_timedwait () from /lib64/libpthread.so.0
#1  0x00000000006205eb in mono_sem_timedwait ()
#2  0x000000000058f5e2 in ?? ()
#3  0x000000000058a906 in ?? ()
#4  0x00000000006251fe in ?? ()
#5  0x00007f139b8ff3a4 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f139b64686d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f139c413780 (LWP 28391)):
#0  0x00007f139b906c39 in waitpid () from /lib64/libpthread.so.0
#1  0x00000000004b8255 in ?? ()
#2  <signal handler called>
#3  0x00007f139b593e77 in raise () from /lib64/libc.so.6
#4  0x00007f139b59527a in abort () from /lib64/libc.so.6
#5  0x00007f139b5d1d24 in ?? () from /lib64/libc.so.6
#6  0x00007f139b656a67 in __fortify_fail () from /lib64/libc.so.6
#7  0x00007f139b65699d in ?? () from /lib64/libc.so.6
#8  0x00007f139b6568f9 in __longjmp_chk () from /lib64/libc.so.6
#9  0x00007f1382176915 in ?? () from /usr/lib64/libcurl.so
#10 <signal handler called>
#11 0x00007f139b63dc8d in poll () from /lib64/libc.so.6
#12 0x0000000040e0a1e6 in ?? ()
#13 0x0000000000000002 in ?? ()
#14 0x00007ffc2c964030 in ?? ()
#15 0x00007f139a802500 in ?? ()
#16 0x00007f13897d8f50 in ?? ()
#17 0x0000000000000002 in ?? ()
#18 0x00007ffc2c964c40 in ?? ()
#19 0x0000000000a0c810 in ?? ()
#20 0x00007ffc2c964030 in ?? ()
#21 0x00007ffc2c964030 in ?? ()
#22 0x00007ffc2c963610 in ?? ()
#23 0x00007f139a802520 in ?? ()
#24 0x00007ffc2c960001 in ?? ()
#25 0x00007ffc2c964030 in ?? ()
#26 0x0000000040e09368 in ?? ()
#27 0x0000000000a11770 in ?? ()
#28 0x00007ffc2c964030 in ?? ()
#29 0x00007f13893d48c0 in ?? ()
#30 0x00007f1389588410 in ?? ()
#31 0x00007f13893d48c0 in ?? ()
#32 0x00007f1389588410 in ?? ()
#33 0x000000000000000f in ?? ()
#34 0x00007f139a802528 in ?? ()
#35 0x0000000040dd5c19 in ?? ()
#36 0x0000000040dd5c64 in ?? ()
#37 0x00007f1300000006 in ?? ()
#38 0x000000000001ed6e in ?? ()
#39 0x0000000000000000 in ?? ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by valuial** [comment]
Versions:
mono 4.0.1.34
glibc 2.20
ckan v1.8.4-0-gf17dfb5 (beta)

(sorry, should have used some pastebin, didn't realize the dump was that long.)

**Comment by Postremus** [comment]
What Operating system do you use?

**Comment by valuial** [comment]
Oh right. Linux. It's a Gentoo system.

**Comment by valuial** [comment]
Um, haven't run Win7 for ages. I'd need to set up KSP for that again, I guess... Won't be today though.

**Comment by Postremus** [comment]
I guess you are in the wrong issue?

**Comment by valuial** [comment]
might be. XD
Happens if you just look halfheartedly at the second screen >,<

**Comment by pjf** [comment]
Just checking if you can reproduce this (or have seen it again at all) with the 1.10.x releases?

**Comment by valuial** [comment]
Started ckan 1.10.3 in GUI mode and had it run in the background (where it crashes mostly) for several hours.
Then updated some mods. Back into background and it crashed within about 20 minutes.
http://pastebin.com/Jf7suMHC

Not sure if this can be a mono problem? Gentoo has mono masked/unstable for any halfway recent version. Currently I use mono version 4.0.1. I could try merging a live build from the mono git. Or some older mono 3 version...
