### ISSUE TITLE
Repeatedly hitting 'Cancel' from the 'Choose Recommended Mods' tab crashes GUI in certain instances

### ISSUE THREAD

**Issue by space-is-hard** [KSP-CKAN/CKAN#1262]
Log of crash: http://pastebin.com/xcz9NY83

Steps to reproduce:

1. Open CKAN GUI in Windows
2. Check _Real Solar System_
3. Select a texture pack and hit _Continue_
4. Click _Go To Changes_ button
5. Click _Apply_ button
6. Click _Cancel_ button in _Choose Recommended Mods_ tab

Expected result: Either CKAN returns to _Changeset_ tab OR to the modlist

Actual result: User is returned to blank _Choose Recommended Mods_ tab. Further clicks of _Cancel_ or _Continue_ buttons return the user to the _Choose Mods_ tab with the texture packs, however the _Continue_ button is disabled. Yet further clicks of the _Cancel_ button throw the error message linked to above.

```
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Postremus** [comment]
Thanks for reporting this. fixed in 1.10.1

**Comment by Postremus** [comment]
uhrg, not closed. wrong issue. sorry.

**Comment by HebaruSan** [comment]
At the time this was submitted, cancelling the recommendations screen would still take you to the suggestions screen, if there were any. The actual cancellation only happened after you finished the suggestions screen as well:

https://github.com/KSP-CKAN/CKAN/blob/ee83a53e1e25e5ef28183a2998e2a805c21e5b8d/GUI/MainInstall.cs#L139-L190

https://github.com/KSP-CKAN/CKAN/blob/ee83a53e1e25e5ef28183a2998e2a805c21e5b8d/GUI/MainInstall.cs#L571-L579

The logic to determine whether to show the suggestions screen was more permissive than the logic to resolve the actual specific items to suggest, so it was possible to get just a blank suggestions screen if none of the suggestions were actually installable:

https://github.com/KSP-CKAN/CKAN/blob/ee83a53e1e25e5ef28183a2998e2a805c21e5b8d/GUI/MainInstall.cs#L468-L552

At the time this was submitted, the latest version of RSS suggested only `RemoteTech-Config-RSS`, which depended on `RemoteTech`, which was only marked as compatible with KSP 1.0.4. We don't know what game version or compatibility settings this user was using, but if it didn't include KSP 1.0.4, then the `RemoteTech-Config-RSS` suggestion would have been excluded from the suggestions screen, which would have been displayed anyway. Empty. And regardless of whether you click cancel or continue, the next action would be cancellation of the install, since `installCanceled` was set to true when cancel was clicked for the recommendations.

So that's a plausible explanation of the first part of this.

The second appearance of the texture pack choice prompt _might_ be a consequence of cancelling and returning to the mod list, since the mod list used to present that prompt itself, outside of an ongoing install (as the early steps of this issue reminded me)? And further issues there would likely be due to that screen not being re-initialized properly, such that the previous task is used again without being reset.

Almost all of this is completely changed by now, and this issue no longer occurs.
