### ISSUE TITLE
"System.NotSupportedException: The given path's format is not supported" when archive contains files with illegal filenames

### ISSUE THREAD

**Issue by draeath** [KSP-CKAN/CKAN#1364]
Got this when attempting to update HullcamVDS from 0.40 to 0.50.

Long story short, there's a few 0-byte files in the archive named "Thumbs.db:encryptable" that blow CKAN up. Adding them to the exclusions (as other Thumbs.db trash files are handled for other mods) fixes.

I'm going to submit a pull request to fix this mod, if I can figure out how, but here's the crash details, and a delta of the registry.json that fixed it.

Handling of invalid filenames (eg, contains junk characters) should at least be caught in some fashion, instead of falling through to System.NotSupportedException.

```
C:\Users\draeath>l:\gamestuff\KSP-stuff\ckan.exe install HullcamVDS
About to install...

 * HullcamVDS 0.50

Continue? [Y/n] y

Downloading "https://kerbalstuff.com/mod/450/Hullcam VDS/download/0.50"
0 kbps - downloading - 0 MiB left - 100%
Installing mod "HullcamVDS 0.50"
Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at CKAN.ModuleInstaller.CopyZipEntry(ZipFile zipfile, ZipEntry entry, String fullPath, Boolean makeDirs)
   at CKAN.ModuleInstaller.InstallModule(CkanModule module, String zip_filename)
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.CmdLine.Install.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

```
--- C:/Users/draeath/Desktop/registry-broke.json    Sun Aug 09 21:00:55 2015
+++ C:/Users/draeath/Desktop/registry-fixed.json    Sun Aug 09 21:00:46 2015
@@ -67167,12 +67167,17 @@
                        {
                            "file": "HullCameraVDS",
                            "find": null,
                            "find_regexp": null,
                            "install_to": "GameData",
-                           "filter": null,
-                           "filter_regexp": null
+                           "filter": [
+                               "Thumbs.db",
+                               "Thumbs.db:encryptable"
+                           ],
+                           "filter_regexp": [
+                               "ModuleManager.*dll$"
+                           ]
                        }
                    ],
                    "spec_version": "1",
                    "abstract": "Hullcam let's you add cameras to any part of your vehicle or construction.",
                    "description": null,
@@ -67180,11 +67185,15 @@
                    "author": [
                        "Albert_VDS"
                    ],
                    "comment": null,
                    "conflicts": null,
-                   "depends": null,
+                   "depends": [
+                       {
+                           "name": "ModuleManager"
+                       }
+                   ],
                    "download": "https://kerbalstuff.com/mod/450/Hullcam%20VDS/download/0.50",
                    "download_size": 5318377,
                    "identifier": "HullcamVDS",
                    "ksp_version": "1.0.4",
                    "ksp_version_max": null,
```

**Comment by draeath** [comment]
I'm afraid I don't know what's wrong syntactically and could use some help fixing.

**Comment by draeath** [comment]
That PR merge should stop this instance from blowing up... but I'd consider the issue still open as if such a file was included anywhere else it would recur.

**Comment by HebaruSan** [comment]
We saw this again recently with #2467, though we have more ZIP validation now and `System.ArgumentException` was thrown instead. I thought about code changes, but I didn't like the idea of hard-coding knowledge about specific operating systems' file systems' limitations.

Catching that exception here might be a good idea:

https://github.com/KSP-CKAN/CKAN/blob/e825bdef9d52a4117e37acf6b6b74da216ee4567/Core/Net/NetFileCache.cs#L271
