### ISSUE TITLE
Crash generated when selecting a mod that conflicts with an installed mod, then un-selecting the installed mod

### ISSUE THREAD

**Issue by TinyPirate** [KSP-CKAN/CKAN#1459]
Bug crashes CKAN. Here's how you repeat it.

1) Install "Custom clusters stock..."
2) tick the other "custom clusters" mod (the stock one goes red)
3) untick the red one.

BOOM

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Mod CustomClusters-StockAdapterStandalone is not in the list
   at CKAN.RelationshipResolver.ReasonFor(Module mod)
   at CKAN.RelationshipResolver.ReasonStringFor(Module mod)
   at CKAN.RelationshipResolver.get_ConflictList()
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KSPVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
```

**Comment by plague006** [comment]
Unable to reproduce. I tried installing `CustomClusters` and then ticking/unticking `CustomClusters-StockAdapterStandalone` without issue. I also tried installing `CustomClusters-StockAdapterStandalone` and then ticking/unticking `CustomClusters`.

What version of CKAN are you running?

**Comment by plague006** [comment]
#1424 should address this.

**Comment by TinyPirate** [comment]
Sounds like this will be wrapped up elsewhere. For the record, you didn't test the same way I did. First, tick "custom clusters" and install it. Then tick "custom clusters - stand alone" - now both are ticked, but the original, installed one is red. Now untick that red one - that causes the crash. Am on the latest release of CKAN. Good luck!

**Comment by plague006** [comment]
Quite right actually, they're 2 different bugs with 2 different reproduction processes. A did a quick test and #1424 won't address this.

**Comment by HebaruSan** [comment]
No longer seems to happen (AECS conflicts with SmartActuation):

![image](https://user-images.githubusercontent.com/1559108/57344536-276b6380-7137-11e9-9df0-5bdf6ce4ebb0.png)
