### ISSUE TITLE
netkan doesn't work, trying to verify a submit.

### ISSUE THREAD

**Issue by qm3ster** [KSP-CKAN/CKAN#1482]
Here is what I attack.
```
{
    "spec_version" : 1,
    "identifier"   : "KerbalFoundries",
    "$kref"        : "#/ckan/kerbalstuff/58",
    "x_netkan_license_ok": true
}
```
And here is what I get.
```
netkan.exe --verbose --debug KerbalFoundries.netkan
65 [1] INFO CKAN.NetKAN.Program (null) - Transforming KerbalFoundries.netkan
101 [1] INFO CKAN.NetKAN.Program (null) - Using CKAN cache at C:/SteamLibrary/SteamApps/common/Kerbal Space Program/CKAN/downloads
111 [1] FATAL CKAN.NetKAN.Program (null) - Unexpected character encountered while parsing value: M. Path '', line 0, position 0.
116 [1] FATAL CKAN.NetKAN.Program (null) -    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at CKAN.NetKAN.Program.ReadNetkan()
   at CKAN.NetKAN.Program.Main(String[] args)
```

**Comment by plague006** [comment]
Unable to replicate the issue, I get a clean .ckan as output.

Ensure that you have the latest netkan artifact from https://ckan-travis.s3.amazonaws.com/netkan.exe and if the issue persists, please let us know your OS.

**Comment by qm3ster** [comment]
My bad. Input file was corrupted.
