### ISSUE TITLE
ArgumentException when unchecking a conflicting mod (Mod x is not in the list)

### ISSUE THREAD

**Issue by nimobeeren** [KSP-CKAN/CKAN#1511]
I currently have FASA installed. I would like to uninstall FASA and install FASA Launch Clamps instead.

When I check FASA Launch Clamps, FASA shows red in the mod list. When I then uncheck FASA, an ArgumentException is thrown: Mod FASA is not in the list ([full exception text](http://pastebin.com/4svx3Pty)).

This also happens when I uncheck FASA first, and then check FASA Launch Clamps.

Applying changes after unchecking FASA, then installing the launch clamps does work.

Also happens when swapping Active Texture Management Basic for the aggressive version.

**Comment by plague006** [comment]
Does this issue persist?

**Comment by draeath** [comment]
Hey,

I'm running into this exact bug with v1.18.0-0-geeb9127

In particular, I have "RSSTextures8192" and I am unable to replace it with either of the other resolution verisons (eg "RSSTextures4096"). Either I have to remove it (and thus everything it depends on gets yanked out too - I see no way to tell it not to do this) or, if I try in the GUI to check 4096 then uncheck 8192 I get:

    System.ArgumentException: Mod RSSTextures8192 is not in the list
       at CKAN.RelationshipResolver.ReasonFor(CkanModule mod)
       at CKAN.RelationshipResolver.ReasonStringFor(CkanModule mod)
       at CKAN.RelationshipResolver.get_ConflictList()
       at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersion ksp_version)
       at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

**Comment by politas** [comment]
Yes, the only way at the moment to replace a dependency is to uninstall all and reinstall. I think we have an issue for that, but I can't find it now.
