### ISSUE TITLE
Unhandled Exception: Cannot install QuickExit, module not available.

### ISSUE THREAD

**Issue by rundmcarlson** [KSP-CKAN/CKAN#1618]
**CKAN Version:** 
1.16.0-g7206ce5

**Operating System:** 
Windows 10 Pro x64

**The issue you are experiencing:** 
When I try to update planetshine (and some other mods) the unhandled exception error comes up as soon as I click the checkbox to update.

**How to recreate this issue:** 
Open CKAN and select installation. Click checkbox to update planetshine.

**CKAN error codes (if applicable):** 
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Cannot install QuickExit, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KSPVersion ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KSPVersion kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KSPVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by politas** [comment]
Don't know if you're still having this problem. I suspect forcing a contents download of QuickExit will resolve this. (Switch to the contents pane on the right and click the download button)

**Comment by rundmcarlson** [comment]
I circumvented the issue by simply using a new install of the game in a different directory and reinstalling all the mods that did not give me issue. I just tried this however, and it seemed to work correctly without crashing. Thank you for the help.
