### ISSUE TITLE
Crash when reinstalling a mod after cleaning cache

### ISSUE THREAD

**Issue by trakos** [KSP-CKAN/CKAN#1658]
**CKAN Version:** 
1.16.1

**Operating System:** 
Windows 7 x64 Professional SP1

**The issue you are experiencing:** 
CKAN crashes when reinstalling the mod after the cache has been cleaned.

**How to recreate this issue:** 
1. Click "Download" on Contents tab of a mod (or just install and remove a mod).
2. Go to Settings -> CKAN settings and click "Clear cache"
3. Check the same mod and try to install it

**CKAN error codes (if applicable):** 
```
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\GalaxyClient\Games\Kerbal Space Program\CKAN\downloads\2BBA8A7C-xScience-4.14.zip'.
File name: 'C:\Program Files (x86)\GalaxyClient\Games\Kerbal Space Program\CKAN\downloads\2BBA8A7C-xScience-4.14.zip'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at CKAN.NetFileCache.GetCachedZip(Uri url, Boolean test_data)
   at CKAN.ModuleInstaller.GetModuleContentsList(CkanModule module)
   at CKAN.Main._UpdateModContentsTree(Boolean force)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.UpdateModContentsTree(CkanModule module, Boolean force)
   at CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
   at CKAN.Main._UpdateFilters()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.PostInstallMods(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
```

**Comment by trakos** [comment]
This bug has been submitted to me on CKAN fork: https://github.com/trakos/CFAN/issues/2 , so I can't take any credit ;)

I think clearing the cache does not call FileSystemWatcher for me. I'm not sure why it's that way, but I've read FileSystemWatcher is not entirely reliable. I'm not sure if it's just that?

Anyway, on my fork I fixed for now simply by re-checking whether file actually exists when getting it:
https://github.com/trakos/CFAN/commit/438dd92e6e957032fbf3e575fcb711339327ba6c . If you want, I can create pull request with this change, but I'm not sure if that's the best way to handle it?

**Comment by politas** [comment]
Looks like the in-memory list of cached mods doesn't even get updated for Windows users.

**Comment by politas** [comment]
I think we should jsut take out the FileSystemWatcher code and re-build the list of cached mods every time we want to check it.
