### ISSUE TITLE
Crash when Downloading Contents of multiple mods simultaneously

### ISSUE THREAD

**Issue by PiggyWhiskey** [KSP-CKAN/CKAN#1713]
CKAN 1.16.1.0
Windows 10

Downloading simultaneous contents of mods to cache causes crash

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
   at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
   at CKAN.Main.ContentsDownloadButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

As a workaround to https://github.com/KSP-CKAN/CKAN/issues/1688 and https://github.com/KSP-CKAN/CKAN/issues/1367 I delete the actual GameData folder before updating a mod (100% success rate at the moment).
Most mods have a common sense folder, but others aren't.
So Downloading the contents is the only way to find exactly what folders.
This takes time, and can't be bulk selected.
Selecting one, and immediately going back to "Manage Mods" and downloading a second causes this crash.

No known workaround except do it one at a time.

**Comment by politas** [comment]
How are you even doing that? I didn't think you could switch away from the downloading screen. You're talking about multiple processes trying to update the same file simultaneously, and this is not a fancy database. Don't do that. Download them one at a time, or

**Comment by PiggyWhiskey** [comment]
Is it possible to select multiple mods to download the cache?

**Comment by politas** [comment]
I don't know of a way to do that, currently. Would you like to turn this into a feature request for that functionality?

**Comment by PiggyWhiskey** [comment]
It's a "nice to have" kind of thing. Nothing super important.

As a feature, it could also be used to bulk select/unselect mods.
