### ISSUE TITLE
Crash on self conflicts

### ISSUE THREAD

**Issue by PiggyWhiskey** [KSP-CKAN/CKAN#1724]
CKAN 1.16.1
Windows 10

Updating Scatterer which adds a new component (scatterer - sunflare)
After digging into the registry, Scatterer-sunflare conflicts with Scatterer-sunflare

Scatterer 2:v0.245 and 2:v0.0246 depend on Scatterer-sunflare

**Comment by PiggyWhiskey** [comment]
Forgot the error:
```
************** Exception Text **************
CKAN.TooManyModsProvideKraken: Too many mods provide Scatterer-sunflare:
Scatterer-sunflare 2:v0.0246
* AstronikiSunflareforScatterer 1.1
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KSPVersion kspversion)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, IDownloader netAsyncDownloader)
   at CKAN.Main.WasSuccessful(Action action)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

Steps to reproduce.
1. Have scatterer 2:v0.0244 installed
2. Update to 2:v0.0246
3. Select either of the mandatory mods ("scatterer - sunflare" OR "Astroniki Sunflare for Scatterer")
4. Click Continue and attempt to update

**Comment by PiggyWhiskey** [comment]
Successful Workaround,

1. Uninstall Scatterer
2. Install additional mod ("scatterer - sunflare" OR "Astroniki Sunflare for Scatterer")
3. Install Scatterer

**Comment by politas** [comment]
Not a bug. Just a change in metadata that means Scatterer needs to be uninstalled and reinstalled.
