### ISSUE TITLE
CKAN crash if Module Manager is missing and is a dependancy.

### ISSUE THREAD

**Issue by Sandriell** [KSP-CKAN/CKAN#1812]
**CKAN Version:** 1.18.0-0-geeb9127 (beta)

**Operating System:** Windows 10

**The issue you are experiencing:** Had installed Module Manager manually, wanted to have CKAN take over handling it, so I deleted the files. Now CKAN crashes. No way to have it take over.

**How to recreate this issue:** Install any mod that depends on Module Manager. Remove Module Manager.

**CKAN error codes (if applicable):**
```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
The following inconsistencies were found:
SCANsat requires ModuleManager but nothing provides it
 * Antennas requires ModuleManager but nothing provides it
 * B9PartSwitch requires ModuleManager but nothing provides it
 * ContractConfigurator-AnomalySurveyor requires ModuleManager but nothing provides it
 * KAS requires ModuleManager but nothing provides it
 * Kopernicus requires ModuleManager but nothing provides it
 * ContractConfigurator-KerbinSpaceStation requires ModuleManager but nothing provides it
 * ContractConfigurator-UnmannedContracts requires ModuleManager but nothing provides it
 * AmpYearPowerManager requires ModuleManager but nothing provides it
 * DecoupleFromHeatshield requires ModuleManager but nothing provides it
 * DefaultActionGroups requires ModuleManager but nothing provides it
 * DockingPortAlignmentIndicator requires ModuleManager but nothing provides it
 * EngineLighting requires ModuleManager but nothing provides it
 * EVAHandrailsPackContinued requires ModuleManager but nothing provides it
 * RasterPropMonitor requires ModuleManager but nothing provides it
 * OuterPlanetsMod requires ModuleManager but nothing provides it
 * RasterPropMonitor-Core requires ModuleManager but nothing provides it
 * FuelTanksPlus requires ModuleManager but nothing provides it
 * HeatControl requires ModuleManager but nothing provides it
 * IndicatorLights requires ModuleManager but nothing provides it
 * ContractConfigurator-Tourism requires ModuleManager but nothing provides it
 * ContractConfigurator-FieldResearch requires ModuleManager but nothing provides it
 * Mk2Expansion requires ModuleManager but nothing provides it
 * InterstellarFuelSwitch requires ModuleManager but nothing provides it
 * HideEmptyTechNodes requires ModuleManager but nothing provides it
 * KWRocketryRedux requires ModuleManager but nothing provides it
 * LithobrakeExplorationTechnologies requires ModuleManager but nothing provides it
 * NearFutureElectrical requires ModuleManager but nothing provides it
 * NearFuturePropulsion requires ModuleManager but nothing provides it
 * RCSSounds requires ModuleManager but nothing provides it
 * RealPlume requires ModuleManager but nothing provides it
 * RoverWheelSounds requires ModuleManager but nothing provides it
 * SpaceY-Expanded requires ModuleManager but nothing provides it
 * SpaceY-Lifters requires ModuleManager but nothing provides it
 * TALSphericalToroidalPack requires ModuleManager but nothing provides it
 * UnmannedBeforeManned requires ModuleManager but nothing provides it
 * VenStockRevamp requires ModuleManager but nothing provides it
 * ContractConfigurator-CleverSats requires ModuleManager but nothing provides it
 * CryoEngines requires ModuleManager but nothing provides it
 * CryoTanks requires ModuleManager but nothing provides it
 * KerbalAtomics requires ModuleManager but nothing provides it
 * DeepFreeze requires ModuleManager but nothing provides it
 * ExtraPlanetaryLaunchpads requires ModuleManager but nothing provides it   at CKAN.SanityChecker.EnforceConsistency(IEnumerable`1 modules, IEnumerable`1 dlls)
   at CKAN.RegistryManager.Save(Boolean enforce_consistency, Boolean recommmends, Boolean with_versions)
   at CKAN.Main.UpdateRepo()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/GlaDOS/Documents/Downloads/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by politas** [comment]
Currently, the only solution is to reinstall Module Manager manually, export your list of mods, uninstall everything that depends on Module Manager, then remove Module Manager manually and reinstall everything in CKAN using the CKAN you created by exporting.
