### ISSUE TITLE
Erroring while installing lots of mods

### ISSUE THREAD

**Issue by PetertheGray** [KSP-CKAN/CKAN#1858]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

v1.18.1-0-g0d2c4f0 (beta)

Windows 10 

CKAN errors while installing a large amount of mods, I was installing 14 mods. updating two.

Install lots of mods.
 
Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\******\AppData\Local\Temp\tmp2733.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetFileCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncModulesDownloader.<DownloadModules>c__AnonStorey0.<>m__0(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.triggerCompleted(Uri[] file_urls, String[] file_paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by DinCahill** [comment]
Thanks for reporting this issue. If you can give us the exact list of mods you were installing and updating, that would help us recreate the issue on our own machines.

**Comment by politas** [comment]
This is a known bug. Updating and installing mods at the same time causes an error. Do your installations and upgrades separately, and you should be fine.

**Comment by PetertheGray** [comment]
Okay, thank you.
