### ISSUE TITLE
Uninstalled all mods but CKAN still thinks I have them

### ISSUE THREAD

**Issue by Gameslinx** [KSP-CKAN/CKAN#1921]
Version:
1.20.1-0-gd41fe54

OS:
Windows 10

Since pressing 'add updates' didn't show anything in the changeset tab, I removed all the mods via deleting the folders in GAMEDATA. This was because nothing would update and I couldn't install mods since the changeset was blank when I pressed 'apply'! I thought this was caused because 'mk3 stockalike expansion' created 'independencies'? Well, I deleted that mod completely and it still gave me that message.
So I deleted every mod and re-downloaded the game and CKAN. No luck! CKAN STILL thinks I have all those mods installed (as they appear under 'installed'. What's more is that now every mod that relied on ModuleManager and IntersetllarFuelSwitch is reporting independencies (because they're deleted)

So please help, because now I cannot use CKAN because I 'apply' doesn't actually apply, and it thinks I have all my mods installed.

**How to recreate this issue:** 
Uh... Download MK3 stockalike expansion (outside of CKAN. It's not on CKAN) and Interstellar fuel switch, then run CKAN? I can't exactly reproduce this issue because *ahem* I can't use CKAN

**CKAN error codes (if applicable):** 
Errors from repositories:
The following inconsistencies were found:
- AirplanePlus depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- FuelTanksPlus depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- KAS depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- SpaceY-Lifters depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- TALSphericalToroidalPack depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- USI-EXP depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- IndicatorLights depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- SCANsat depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- SpaceY-Expanded depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
- Mk3Expansion depends on InterstellarFuelSwitch but it is not listed in the index, or not available for your version of KSP.

And this is when trying to open the 'settings' section (which I can):

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
The following inconsistencies were found:
AirplanePlus depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * FuelTanksPlus depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * KAS depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * SpaceY-Lifters depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * TALSphericalToroidalPack depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * USI-EXP depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * IndicatorLights depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * SCANsat depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * SpaceY-Expanded depends on ModuleManager but it is not listed in the index, or not available for your version of KSP.
 * Mk3Expansion depends on InterstellarFuelSwitch but it is not listed in the index, or not available for your version of KSP.   at CKAN.SanityChecker.EnforceConsistency(IEnumerable`1 modules, IEnumerable`1 dlls)
   at CKAN.RegistryManager.Save(Boolean enforce_consistency, Boolean recommmends, Boolean with_versions)
   at CKAN.SettingsDialog.RefreshReposListBox()
   at CKAN.SettingsDialog.UpdateDialog()
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Casper/Downloads/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Gameslinx** [comment]
Additional:
It seems that after deleting the CKAN directory, it works again. But I still think this is a serious issue.

**Comment by Olympic1** [comment]
Because you deleted the mods manually instead of using CKAN, it never registered that they were deleted. When installing a new mod it suddenly noticed that the mods were missing from the GameData folder and errors.
