### ISSUE TITLE
Mod SVE-High Resolution is not in the list.

### ISSUE THREAD

**Issue by jcsntoll** [KSP-CKAN/CKAN#1924]
Thanks for wanting to bring an issue to our attention!
**CKAN Version:** 
v1.20.1-0-gd41fe54 (beta)

**Operating System:** 
Windows 7

**The issue you are experiencing:** 
Unhandled exception - Mod SVE-High Resolution is not in the list.

**How to recreate this issue:** 
Have version 1:1.1.21 instaled and try and update to version 2:1.1.4

**CKAN error codes (if applicable):** 
[http://imgur.com/a/hPjwO](url)

```
************** Exception Text **************
System.ArgumentException: Mod SVE-HighResolution is not in the list
   at CKAN.RelationshipResolver.ReasonFor(CkanModule mod)
   at CKAN.RelationshipResolver.ReasonStringFor(CkanModule mod)
   at CKAN.RelationshipResolver.get_ConflictList()
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by politas** [comment]
Can you try uninstalling and re-installing? There's been a significant change in the SVE metadata.

**Comment by jthill** [comment]
Came to report this issue, the un/reinstall of sve worked around it for me.
