### ISSUE TITLE
CKAN not working I have .net latest version installed

### ISSUE THREAD

**Issue by NizoGTO** [KSP-CKAN/CKAN#1949]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.20.1
**Operating System:** 
Windows 10
**The issue you are experiencing:** 
Unhandled exception
**How to recreate this issue:** 
I open it and its gives me error message
**CKAN error codes (if applicable):** 

````
CKAN.NotKSPDirKraken: Could not find KSP version in readme.txt
   at CKAN.KSP.DetectVersion(String directory)
   at CKAN.KSP.Version()
   at CKAN.Main.<CurrentInstanceUpdated>m__B()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.CurrentInstanceUpdated()
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

**Comment by Dazpoet** [comment]
CKAN doesn't know which version of KSP you are using. You're either missing both the buildID.txt and the readme.txt file in your KSP install or pointing CKAN towards the wrong folder.

If you are using steam please go into properties of KSP and "verify integrity of game cache" and if you are downloading ksp from the squad store check the .zip for the files I mentioned and add them to your ksp folder.
