### ISSUE TITLE
CKAN.FileExistsKraken

### ISSUE THREAD

**Issue by jforr** [KSP-CKAN/CKAN#1962]
**CKAN Version:** 
You are using CKAN version v1.20.1-0-gd41fe54 (beta)

**CKAN error codes (if applicable):** 

E:\KSP\KSP_1.2.1>ckan upgrade --all

Upgrading modules...

Unhandled Exception: CKAN.FileExistsKraken: Trying to write E:/KSP/KSP_1.2.1/GameData/UmbraSpaceIndustries/KarbonitePlus/ATM.cfg but it already exists.
   at CKAN.ModuleInstaller.CopyZipEntry(ZipFile zipfile, ZipEntry entry, String fullPath, Boolean makeDirs)
   at CKAN.ModuleInstaller.InstallModule(CkanModule module, String zip_filename)
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove, Boolean enforceConsistency)
   at CKAN.CmdLine.Upgrade.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.RunAction(Options cmdline, CommonOptions options, String[] args, IUser user, KSPManager manager)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by politas** [comment]
Please try uninstalling KarbonitePlus and then reinstalling

**Comment by jforr** [comment]
After reading the forums it appears that KarbonitePlus and Karbonite have been merged into one mod which caused the above error.

This is probably a really odd scenario that might never occur again, but it might be worth exploring the implications of two mods merging files and becoming one.

**Comment by Sxderp** [comment]
@jforr File 'merging' would be a pretty bad idea for a mod manager. It could lead to incompatibilities. The current 'abort if exists' is probably the best option. Though, handling it more gracefully may be nice (list which mod is conflicting in easy to read format, etc).
