### ISSUE TITLE
Exception of type 'CKAN.ModuleNotFoundKraken' when opening one of my installs

### ISSUE THREAD

**Issue by CrawdadCletis** [KSP-CKAN/CKAN#1982]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
v1.22.1-0-g174271a (beta)

**Operating System:** 
Windows 10 Home 64-bit

**The issue you are experiencing:** 
CKAN throws "CKAN.ModuleNotFoundKraken" when I open one of my installs.  The others work fine.  It isn't obvious if it is referring to a specific mod.

**How to recreate this issue:** 
Open the attached ckan install.
[CKAN.zip](https://github.com/KSP-CKAN/CKAN/files/705202/CKAN.zip)

**CKAN error codes (if applicable):** 
![image](https://cloud.githubusercontent.com/assets/13510940/21943792/707d93ba-d998-11e6-87b2-34690505c4ce.png)

````
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
   at CKAN.Registry.AllAvailable(String module)
   at CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
   at CKAN.MainModInfo.set_SelectedModule(GUIMod value)
   at CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   at System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   at System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   at System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
   at CKAN.Main._UpdateFilters()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main._UpdateModsList(Boolean repo_updated)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.CurrentInstanceUpdated()
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

**Comment by rymonte** [comment]
Does this happen and startup and when you try to perform any action within CKAN? If so I'm having the exact same issue.

**Comment by CrawdadCletis** [comment]
Yes, this happens for me on startup.  If I hit "Continue", it happens again and again for most actions in CKAN (select a mod, update, etc).

If I switch to another ckan install, it stops happen.  If I change my default ckan install (so that the bad one isn't automatically loaded when I startup), then it doesn't happen at startup any more.

**Comment by denyasis** [comment]
Hello. I am having what appears to be the same issue on Linux Debian Testing:

**CKAN VERSION:** v1.22.1-0-g174271a (beta)

**Operating System:** Debian Testing: 4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux

**MONO Version:** Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)

**The issue you are experiencing:** 
**CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown** When I try to start CKAN.exe The program then fails to start. I do notice that the Window frame of the GUI starts to render just before the error is thrown and the program crashes.

CKAN was working this morning with out issue. 

Thanks for taking the time to look at this.

Here is the terminal output:

`CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
  at CKAN.Registry.AllAvailable (System.String module) [0x00034] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.MainAllModVersions.set_SelectedModule (CKAN.GUIMod value) [0x0003a] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at (wrapper remoting-invoke-with-check) CKAN.MainAllModVersions:set_SelectedModule (CKAN.GUIMod)
  at CKAN.MainModInfo.set_SelectedModule (CKAN.GUIMod value) [0x00061] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at (wrapper remoting-invoke-with-check) CKAN.MainModInfo:set_SelectedModule (CKAN.GUIMod)
  at CKAN.Main.ModList_SelectedIndexChanged (System.Object sender, System.EventArgs e) [0x00019] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at System.Windows.Forms.DataGridView.OnSelectionChanged (System.EventArgs e) [0x0001c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.DataGridView.SetSelectedRowCore (System.Int32 rowIndex, System.Boolean selected) [0x00082] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at CKAN.MainModListGUI.SetSelectedRowCore (System.Int32 rowIndex, System.Boolean selected) [0x0001e] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at System.Windows.Forms.DataGridView.MoveCurrentCell (System.Int32 x, System.Int32 y, System.Boolean select, System.Boolean isControl, System.Boolean isShift, System.Boolean scroll) [0x0058a] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.DataGridView.OnRowsAddedInternal (System.Windows.Forms.DataGridViewRowsAddedEventArgs e) [0x00073] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView:OnRowsAddedInternal (System.Windows.Forms.DataGridViewRowsAddedEventArgs)
  at System.Windows.Forms.DataGridViewRowCollection.AddRange (System.Windows.Forms.DataGridViewRow[] dataGridViewRows) [0x00069] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at CKAN.Main._UpdateFilters () [0x0011c] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Util.Invoke[T] (T obj, System.Action action) [0x00035] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main.UpdateFilters (CKAN.Main control) [0x00001] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main._UpdateModsList (System.Boolean repo_updated) [0x00440] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main+<UpdateModsList>c__AnonStorey10.<>m__0 () [0x00000] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Util.Invoke[T] (T obj, System.Action action) [0x00035] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main.UpdateModsList (System.Boolean repo_updated) [0x00015] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main.CurrentInstanceUpdated () [0x00062] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main.OnLoad (System.EventArgs e) [0x00248] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) [0x00029] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
`

**Comment by denyasis** [comment]
Hello again-

I think I might have a fix/workaround for my issue, although I have no clue as to why it works. Since the command line works, I started playing around with the command line. I ran:

`mono ckan.exe update`

I got the following response:
```
Downloading updates...
Updated information on 683 available modules
```

I then tried to launch the GUI from the command line
and the GUI launches properly with out error.

I exited the program and ran 
`mono ckan.exe`
and the program loaded the gui. No errors thrown. Refreshing the repo data seemed to have fixed the issue, although I have no idea why.

I hope that helps

**Comment by CrawdadCletis** [comment]
The workaround from denyasis works for me too.  After doing the "ckan update" from the command line, I can safely launch the GUI again.  Good job with the workaround!

**Comment by rymonte** [comment]
Worked for me too. Hopefully this is just a blip and not a problem that's going to recur.

**Comment by politas** [comment]
This might be worth adding to the [Troubleshooting guide](https://github.com/KSP-CKAN/CKAN/wiki/Basic-troubleshooting)

**Comment by politas** [comment]
And that's done. Thanks for the investigation, @CrawdadCletis, and thanks for the confirmation, @rymonte!

**Comment by Yous34** [comment]
no need to use mono, i got the same issue,i'm using win 10 64-bits, i went to the folder where ckan is (my descktop), shift+rmb open Command Window Here, and i typed ckan update and now it works fine

**Comment by Shirkit** [comment]
On my case, I had to delete the Ground Construction mod before the `ckan update` made through the end, it was crashing on the middle of the process.

**Comment by yin** [comment]
Same here, the fix helps

**Comment by Starslinger909** [comment]
Im having the Same issue on Windows 10. It seems to not let me start it up, I get the console error and a message saying:
Unhandled exception:
CKAN.NotKSPDirKraken: Could not find KSP version in buildID.txt or readme.txt
   at CKAN.KSP.CkanDir()
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by HebaruSan** [comment]
Hi @Starslinger909, that's a different problem. The people having this issue were missing the available modules list, whereas you have a problem with your KSP folder. Try the workaround discussed in #2275 to reset your path to KSP.

**Comment by Shane54NZ** [comment]
Yous34's comment from 20 Jan fixed the issue for me as well. Awesome, thanks kindly! :-)
