### ISSUE TITLE
Detect and correct an empty available_modules in the registry when mods are installed

### ISSUE THREAD

**Issue by MBradbury** [KSP-CKAN/CKAN#1994]
**CKAN Version:** 
master (https://github.com/KSP-CKAN/CKAN/commit/683fa13bb8f8a6895f4a6d562316eb006ada6f5a)

**Operating System:** 
Windows 10 x64

**The issue you are experiencing:** 

Somehow my registry.json ended up containing '"available_modules": {},' which led to #1992 while trying to diagnose this. When loading CKAN I get the error message shown at the end. MechJeb isn't at fault, it is simply the first mod trying to be found.

I managed to resolve my issue by moving the registry, restarting CKAN and then copying the available_modules from the new registry to the old registry. Ideally CKAN should be able to detect this and refetch available_modules.

```
CKAN.ModuleNotFoundKraken: Module MechJeb2 of version  is not available
   at CKAN.Registry.AllAvailable(String module) in S:\Code\CKAN\Core\Registry\Registry.cs:line 522
   at CKAN.MainAllModVersions.set_SelectedModule(GUIMod value) in S:\Code\CKAN\GUI\MainAllModVersions.cs:line 28
   at CKAN.MainModInfo.set_SelectedModule(GUIMod value) in S:\Code\CKAN\GUI\MainModInfo.cs:line 56
   at CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e) in S:\Code\CKAN\GUI\Main.cs:line 490
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   at System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   at System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   at System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
   at CKAN.Main._UpdateFilters() in S:\Code\CKAN\GUI\MainModList.cs:line 127
   at CKAN.Util.Invoke[T](T obj, Action action) in S:\Code\CKAN\GUI\Util.cs:line 28
   at CKAN.Main.UpdateFilters(Main control) in S:\Code\CKAN\GUI\MainModList.cs:line 18
   at CKAN.Main._UpdateModsList(Boolean repo_updated) in S:\Code\CKAN\GUI\MainModList.cs:line 209
   at CKAN.Main.<>c__DisplayClass233_0.<UpdateModsList>b__0() in S:\Code\CKAN\GUI\MainModList.cs:line 143
   at CKAN.Util.Invoke[T](T obj, Action action) in S:\Code\CKAN\GUI\Util.cs:line 28
   at CKAN.Main.UpdateModsList(Boolean repo_updated) in S:\Code\CKAN\GUI\MainModList.cs:line 143
   at CKAN.Main.CurrentInstanceUpdated() in S:\Code\CKAN\GUI\Main.cs:line 441
   at CKAN.Main.OnLoad(EventArgs e) in S:\Code\CKAN\GUI\Main.cs:line 347
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**How to recreate this issue:** 

I can't reproduce this by simply deleting the contents of available_modules of a new registry, as that does get repopulated. The following is a zip of my registry with the issue [registry.json.bad.txt.zip](https://github.com/KSP-CKAN/CKAN/files/712256/registry.json.bad.txt.zip)

**CKAN error codes (if applicable):**

**Comment by ayan4m1** [comment]
There are valid cases where the registry contains no available modules (there is a static Registry.Empty() which sets the modules arrays empty), so I'm not sure how we would go about making this change.
