### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by Necessarycoot72** [KSP-CKAN/CKAN#1995]
**CKAN Version:** 
1.2.2.1662

**Operating System:** 
windows 10 64bit

The issue you are experiencing:** 
error on startup

How to recreate this issue:
No clue

CKAN error codes
Unhandled exception:
CKAN.Kraken: Error trying to parse "C:/Games/kerbal space program\CKAN/GUIConfig.xml": Root element is missing.. Try to move it out of the folder and restart CKAN.
   at CKAN.Configuration.LoadConfiguration(String path)
   at CKAN.Configuration.LoadOrCreateConfiguration(String path, String defaultRepo)
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Gui(GuiOptions options, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args) 

I removed the guiconfig like it said then this popped up

501 [1] ERROR CKAN.ErrorDialog (null) - Unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.RegistryManager.AscertainDefaultRepo()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Gui(GuiOptions options, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by kriistoff** [comment]
i have exactly the same problem since today.
Also on windows 10. 
Not able to start up ckan.
have you found a way to fix it?

**Comment by linuxgurugamer** [comment]
Try removing the entire CKAN directory in the game folder
