### ISSUE TITLE
CKAN.ModuleNotFoundKraken when finding available versions for mod removed from repos on search

### ISSUE THREAD

**Issue by spirritus** [KSP-CKAN/CKAN#2022]
Hi there,

as of this sunday (march-12) ckan throws this lovely exception when searching for "as" or trying to install a new mod. Any ideas?

Cheers Jens

```
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
   at CKAN.Registry.AllAvailable(String module)
   at CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
   at CKAN.MainModInfo.set_SelectedModule(GUIMod value)
   at CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   at System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   at System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   at System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
   at CKAN.Main._UpdateFilters()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.MainModList.set_ModNameFilter(String value)
   at CKAN.Main.FilterByNameTextBox_TextChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Games/KSP/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
```

**Comment by politas** [comment]
Can you post your registry.json file?

**Comment by spirritus** [comment]
When searching for "as" the first thing selected is "ASET Props - Community Edition".


[registry.json.txt](https://github.com/KSP-CKAN/CKAN/files/846016/registry.json.txt)

**Comment by politas** [comment]
Does it throw the same exception on any search, or just that particular string?

**Comment by spirritus** [comment]
Seems to be only that string for search.
And for the install error that would be: "ASET Avionics", "'MK1-2' IVA Replacementby ASET", "Mk1 Lander Can' IVA Replacement by ASET", "'MK1 Cockpit' IVA Replacement by ASET", "ASET Props", "ASET Avionics", ASET Agency", "ABookCase Orbital Reference System" - at least he ones i tried. (basically all when you search for ase and try to install them"

**Comment by politas** [comment]
Ok, it looks like there's an issue with a mod you have installed, "ASETProps-CE", which conflicts with ASETProps. That mod has been removed from the CKAN repositories, so CKAN is having problems with it.

Run the following from a command line:

    ckan remove ASETProps-CE

Or if you have multiple KSP installs you're managing with CKAN:

    ckan remove ASETProps-CE --ksp <instance>

Where <instance> is the name that you select in the "Select KSP install" screen

**Comment by politas** [comment]
```
44769 [1] DEBUG CKAN.Registry (null) - Finding all available versions for ASETProps-CE
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
  at CKAN.Registry.AllAvailable (System.String module) [0x00034] in <62d6c9286d1540d4955161a23aba206f>:0 
  at CKAN.MainAllModVersions.set_SelectedModule (CKAN.GUIMod value) [0x0003a] in <62d6c9286d1540d4955161a23aba206f>:0 
  at (wrapper remoting-invoke-with-check) CKAN.MainAllModVersions:set_SelectedModule (CKAN.GUIMod)
  at CKAN.MainModInfo.set_SelectedModule (CKAN.GUIMod value) [0x00061] in <62d6c9286d1540d4955161a23aba206f>:0 
  at (wrapper remoting-invoke-with-check) CKAN.MainModInfo:set_SelectedModule (CKAN.GUIMod)
  at CKAN.Main.ModList_SelectedIndexChanged (System.Object sender, System.EventArgs e) [0x00019] in <62d6c9286d1540d4955161a23aba206f>:0 
  at System.Windows.Forms.DataGridView.OnSelectionChanged (System.EventArgs e) [0x0001c] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.DataGridView.SetSelectedRowCore (System.Int32 rowIndex, System.Boolean selected) [0x00082] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at CKAN.MainModListGUI.SetSelectedRowCore (System.Int32 rowIndex, System.Boolean selected) [0x0001e] in <62d6c9286d1540d4955161a23aba206f>:0 
  at System.Windows.Forms.DataGridView.MoveCurrentCell (System.Int32 x, System.Int32 y, System.Boolean select, System.Boolean isControl, System.Boolean isShift, System.Boolean scroll) [0x0058a] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.DataGridView.OnRowsAddedInternal (System.Windows.Forms.DataGridViewRowsAddedEventArgs e) [0x00073] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView:OnRowsAddedInternal (System.Windows.Forms.DataGridViewRowsAddedEventArgs)
  at System.Windows.Forms.DataGridViewRowCollection.AddRange (System.Windows.Forms.DataGridViewRow[] dataGridViewRows) [0x00069] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at CKAN.Main._UpdateFilters () [0x0011c] in <62d6c9286d1540d4955161a23aba206f>:0 
  at CKAN.Util.Invoke[T] (T obj, System.Action action) [0x00035] in <62d6c9286d1540d4955161a23aba206f>:0 
  at CKAN.Main.UpdateFilters (CKAN.Main control) [0x00001] in <62d6c9286d1540d4955161a23aba206f>:0 
  at CKAN.Main.<Main>m__6 (CKAN.MainModList source) [0x00000] in <62d6c9286d1540d4955161a23aba206f>:0 
  at CKAN.MainModList.set_ModNameFilter (System.String value) [0x0001b] in <62d6c9286d1540d4955161a23aba206f>:0 
  at CKAN.Main.FilterByNameTextBox_TextChanged (System.Object sender, System.EventArgs e) [0x0002a] in <62d6c9286d1540d4955161a23aba206f>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_EventArgs (object,System.EventArgs)
  at System.Windows.Forms.Control.OnTextChanged (System.EventArgs e) [0x0001c] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.TextBoxBase.OnTextChanged (System.EventArgs e) [0x00000] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.TextBoxBase.WndProc (System.Windows.Forms.Message& m) [0x0018b] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.TextBox.WndProc (System.Windows.Forms.Message& m) [0x00175] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <e37081a3704b4473a59cdf5048ad96bc>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <e37081a3704b4473a59cdf5048ad96bc>:0 
44792 [1] DEBUG CKAN.RegistryManager (null) - Dispose of registry at /home/politas/Desktop/KSP/KSP-1.2.2/spirritus/CKAN
```

**Comment by politas** [comment]
KSP-CKAN/CKAN-meta#1245 is what triggered this

**Comment by techman83** [comment]
Wow good spotting that one @politas !

**Comment by spirritus** [comment]
That worked, thanks a lot!

**Comment by ayan4m1** [comment]
Related to #2098
