### ISSUE TITLE
Environmental Visual Enhancement can produce CKAN.TooManyModsProvideKraken.

### ISSUE THREAD

**Issue by solarsootysmudge** [KSP-CKAN/CKAN#2026]
Installing Environmental Visual Enhancement can produce CKAN.TooManyModsProvideKraken.
I can install all of these mods by following a different method. Installing scatter first helps. However I suspect that most end users will do this instead.....

**1.** Enviromental Visual Enhancements
Asks for config choice
-EVE config
-SVE High
-SVE low
-SVE Medium

**2**. Select SVE High
Asks for sunflare config
-Scatter sunflare
-Astroniki
-Cepheus
-Eden
-SVE sunflare

**3**. Select Astroniki

Apply changes
Which lists mods to be installed as
EVE 2EVE1.2-2
SVE Highres 2:1.1.6
scatter 2v0.0300
SVE Scatter config 2:1.1.6
Astroniki for scatter 1.2

**5**. Click on apply
Recommends Planet shine
Tick mod

**6**. Click continue
Throws exception
************** Exception Text **************
CKAN.TooManyModsProvideKraken: Too many mods provide Scatterer-config:
Scatterer-config 2:v0.0300

SVE-Scatterer-Config 2:1.1.6
at CKAN.RelationshipResolver.ResolveStanza(IEnumerable1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable1 old_stanza)
at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable1 old_stanza) at CKAN.RelationshipResolver.ResolveStanza(IEnumerable1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable1 old_stanza) at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable1 old_stanza)
at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable1 modules) at CKAN.RelationshipResolver..ctor(IEnumerable1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
at CKAN.ModuleInstaller.InstallList(List1 modules, RelationshipResolverOptions options, IDownloader downloader) at CKAN.Main.WasSuccessful(Action action) at CKAN.Main.InstallList(HashSet1 toInstall, RelationshipResolverOptions options, IDownloader downloader)
at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Further Research.
Installing scatter first before going through the steps avoids problems.

**Comment by solarsootysmudge** [comment]
Have confirmed that if Scatterer is selected first. All the same config files appear for selection and install is completed.  Whilst doing it as above breaks things.

First posted as a possible NetKan issue. Asked to move here by @politas. Just keep everything in one issue report that one has been closed and last comment moved here. Many thanks.

> This is a code issue. Looks like we aren't staying aware of all the changes as we traverse levels of dependency.Can you re-open this as a main repo


Many thanks

**Comment by HebaruSan** [comment]
I believe this was addressed in #2577. `Main.InstallMods` now catches `TooManyModsProvideKraken` and prompts the user to choose.

https://github.com/KSP-CKAN/CKAN/blob/7413c232f2ff7f58692617ae7c3cfa12551a7f6f/GUI/MainInstall.cs#L175-L198
