### ISSUE TITLE
System.NullReferenceException Windows 10

### ISSUE THREAD

**Issue by malk0lm** [KSP-CKAN/CKAN#2037]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Main._MarkModForUpdate(String identifier)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.PostInstallMods(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by Olympic1** [comment]
We need more info to help you. Which mod were you trying to update, which version of CKAN were you using ...

**Comment by malk0lm** [comment]
CKAN v1.22.1-0-g174271a (beta). The mods I am updating are EVE 1.2.2-4 and Stock Visual Enhancements- High Res Textures 2:1.1.6 updated to version 3"1.0

**Comment by Olympic1** [comment]
Ah yeah, to fix this delete everything from SVE and reinstall `Stock Visual Enhancements` and one of the three textures
