### ISSUE TITLE
Could not retrieve build map + error refreshing mod list

### ISSUE THREAD

**Issue by jerr060599** [KSP-CKAN/CKAN#2149]
This bug error seems to pop up no matter which install of KSP I choose, from 1.0.5 to 1.3.0. It was working fine just a few days before, and I see that the change log asks that users report new download issues. I can't seem to get it to work no matter what I do. It fails even on clean KSP installs.

CKAN Version: 1.22.5+b86496408b01

Operating System: Windows 10 x64

The issue you are experiencing: Could not refresh the mod list. 0 Mods in the catalog. 

How to recreate this issue: Attempt to refresh the mod list. 

CKAN error codes (if applicable): 

Trying though console: 
Downloading updates...
468 [1] WARN CKAN.Curl (null) - Curl environment not pre-initialised, performing non-threadsafe init.
484 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - Could not retrieve latest build map from: https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json
Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
Updated information on 0 available modules

On launch with the GUI:
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
   at CKAN.Registry.AllAvailable(String module)
   at CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
   at CKAN.MainModInfo.set_SelectedModule(GUIMod value)
   at CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   at System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   at System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   at System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
   at CKAN.Main._UpdateFilters()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.UpdateFilters(Main control)
   at CKAN.Main._UpdateModsList(Boolean repo_updated)
   at CKAN.Main.<>c__DisplayClass233_0.<UpdateModsList>b__0()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.UpdateModsList(Boolean repo_updated)
   at CKAN.Main.CurrentInstanceUpdated()
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jimduchek** [comment]
I had this same error on Linux, I had started it as root once by accident and it created a /tmp/CdFileMgr/ that I no longer had permissions to write to.  Now, I'm not sure what directory it attempts to save to on Windows, but it may be the case that you don't have permissions to write to it.
