### ISSUE TITLE
File Corrupted and Unreadable

### ISSUE THREAD

**Issue by Bekokaan** [KSP-CKAN/CKAN#2260]
Background
----------

**CKAN Version:** 
1.24

**KSP Version:** 
1.3 i think i cant even open my game 

**Operating System:** 
Win10 64bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
none

Problem
-------

**What steps did you take in CKAN?**

First day insatalled some mods played a little noting bad runs smootly, second day i saw few mods god updated so before the update  played a little more then got a crash so i wanted to update the mods

Searched github and forums but with my little english i couldnt find the soulition and the most of the problems were "same file name , cannot access the file, etc."

1) tryed to reinstall (same)
2)deleting everything (still same)
3)Check for every single update (same)

**What did you expect to happen?**
I did expect to find a soulition but when i started the search it was 1 am. and time im writing this is 9am so i hoped to get a soulition

**What happened instead?**

it gave me a error on 1 one of them after that when i open CKAN i always get this error.

System.IO.IOException: The file or directory is corrupted and unreadable.

System.IO.IOException: The file or directory is corrupted and unreadable.

nothing after the search last hope is opening a isssue

Sorry for my miss spelling and grammer im realy sleepy right now and english is my second language.

Thanks for the help

**Screenshots:**

**CKAN error codes (if applicable):** 

```
************** Exception Text **************
System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at CKAN.KSP.ScanGameData()
   at CKAN.Main.UpdateRepo()
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0
    CodeBase: file:///D:/SteamLibrary/steamapps/common/Kerbal%20Space%20Program/ckan%20(1).exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
```

**Comment by HebaruSan** [comment]
It sounds like one of your files or directories may be corrupted and unreadable. Is it possible you ran KSP as an administrator in the past and then ran it as a normal user when you saw these errors?

**Comment by Bekokaan** [comment]
@HebaruSan i dont think so, always opened it through steam

**Comment by Bekokaan** [comment]
Tryed to reinsatl all the missing file's and the problems is i cant even delete,move or change the file's it says i need permission for this action.

i think something messed up my permissions

**Comment by HebaruSan** [comment]
What happens if you verify the local files for KSP in steam?

https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by Bekokaan** [comment]
there is no problem on validating files.

**Comment by HebaruSan** [comment]
Does KSP work if you reinstall and _don't_ try to use CKAN? This sounds like something wrong at the hardware or operating system level rather than something that could be fixed by changing CKAN's code, but it's hard to say for sure.

**Comment by Bekokaan** [comment]
Tryed it, still nothing its about the operating system i think

**Comment by HebaruSan** [comment]
OK, in that case I'm going to close this as it appears it isn't about a problem with CKAN.
You may want to try KSP support, as it sounds like you have a problem simply running the game by itself. If you're able to resolve that and CKAN still gives you problems, let us know and we can re-open this.
