### ISSUE TITLE
CKAN lose all the selected mods and freeze in the current stage after get 404 error (And maybe others errors)

### ISSUE THREAD

**Issue by ReiDaTecnologia** [KSP-CKAN/CKAN#2274]
### CKAN Version:
Latest (1.22.6 aka Guiana)

### KSP Version: 
1.3.0

### Operating System:
Windows 7 Pro x64 

### Have you made any manual changes to your GameData folder (i.e., not via CKAN)?
No.

### What steps did you take in CKAN?
Use any mod/core with invalid download link like North Kerbin Dynamics (Not invalid download only the Core) and you dependency C.A.L++
Wait until get 404 Error, click in Dismiss
If you select the option: Quit, he will stop responding.
If you select the option: Continue, freeze in the current stage but you can choose another mod to install, sadly you lose all you mods selection and you need choose again if is a big selection you need a superhuman memory to remember :/ (This is the most annoying thing because i not have a really good memory).

### What did you expect to happen?
Continue: Just cancel the download of mod with problem and continue to the others downloads or if is a Core-Mod cancel both, the mod and the required core-mod for this mod (Because this mod can't work without this core).
Quit: Exit the program? but who want this? maybe can be "Cancel" that cancel the operation.

### What happened instead?
Continue option: Stop downloading and freeze in the current state and lose all selected mods.
Quit: Stop Responding.

### CKAN error codes (if applicable):
Before you click Dismiss:
_Error: The remote server returned an error: (404) Not Found._
After:
_Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately
Exception of type 'CKAN.DownloadErrorsKraken' was thrown._
### Details (Really big): **I don't know a way to use "Spoiler" or if have this here**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Uh oh, the following things went wrong when downloading...

System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 1.22.0.0
    Win32 Version: 1.22.6
    CodeBase: file:///C:/Jogos/KSP%20Mod%20Manager/CKAN%20-%20KSP%20Mod%20Manager.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2563.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2623.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2623.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by HebaruSan** [comment]
Not sure exactly what's being reported here, but I do think I've seen the GUI fail to return to the mod list after a download failure in the 1.24PRE versions, leaving the progress tab open instead. It's probably related to #2233, which removed some GUI code that was redundant with some of Core. I need to audit the new and old code to make sure all the fiddly GUI bits were preserved in that transition.

**Comment by ReiDaTecnologia** [comment]
Ok, thanks.

**Comment by HebaruSan** [comment]
OK, on further examination, #2233 made this slightly better rather than worse. Before that pull request, any download exceptions thrown by this code were not caught anywhere, which accounts for the Quit and Continue buttons reported by the OP:

https://github.com/KSP-CKAN/CKAN/blob/28c981e3bf71d3f596cd8f537bf33831e4e8ab36/GUI/MainInstall.cs#L123

Now such exceptions are caught here, which at least means the app doesn't crash, but it's still in a somewhat inconsistent state:

https://github.com/KSP-CKAN/CKAN/blob/bb028923969f731df7b2a66b592ad4c5e9f9baa0/GUI/MainInstall.cs#L197-L201

Specifically, the change set info gets out of sync with the UI; your chosen mods are still selected in the main mod list, and the Apply button is still enabled, but when you click it, the list of mods to install appears blank. I've been trying to investigate exactly how that happens, but it's a rough slog, hence #2276.
