### ISSUE TITLE
Could not find a part of the path 'C:\Users\name\Appdata\Local\Temp\CdFileMgr\02a3e06-bc35-40.json'.

### ISSUE THREAD

**Issue by LadivItnas** [KSP-CKAN/CKAN#2342]
Background
----------

**CKAN Version:**
1.24.0

**KSP Version:**
1.3.1.1819

**Operating System:**
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No.

Problem
-------

**What steps did you take in CKAN?**
Was installing mods: EVE, Scatterer, SVE, Science Full reward, Science alert

**What did you expect to happen?**
Mods being installed 

**What happened instead?**

```
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue, if you click Quit, the application will close immediately.
Could not find a part of the path 'C:\Users\name\Appdata\Local\Temp\CdFileMgr\02a3e06-bc35-40.json'.
```

Screenshots:
![image](https://user-images.githubusercontent.com/26176267/36948860-93784a72-1fbf-11e8-85b9-136dc5e8387b.png)
![image](https://user-images.githubusercontent.com/26176267/36948906-21c84804-1fc0-11e8-81c9-cd109dbaded9.png)
*Progress bar is stuck at 70%

**CKAN error codes (if applicable):**

```
************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\name\AppData\Local\Temp\CdFileMgr\02a3e0a6-bc35-40.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ChinhDo.Transactions.WriteAllTextOperation.Execute()
   at ChinhDo.Transactions.TxFileManager.EnlistOperation(IRollbackableOperation operation)
   at CKAN.RegistryManager.Save(Boolean enforce_consistency)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0
    CodeBase: file:///C:/Users/name/Desktop/ckan.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
```

**Comment by HebaruSan** [comment]
Interesting. Does this happen every time, or was it a one-off? Can you please check whether these folders exist?

- C:\Users\name\Appdata
- C:\Users\name\Appdata\Local
- C:\Users\name\Appdata\Local\Temp

**Comment by HebaruSan** [comment]
Thanks, what about C:\Users\name\Appdata\Local\Temp\CdFileMgr ?

**Comment by LadivItnas** [comment]
Oh no it's not there

**Comment by LadivItnas** [comment]
How do I get it back there?

**Comment by HebaruSan** [comment]
That's quite strange! The Transactions library attempts to create that folder if it doesn't exist:

https://github.com/rsevil/Transactions/blob/8125415d5a74eb129d2d0311762362dfa2679193/src/ChinhDo.Transactions.FileManager/TxFileManager.cs#L16-L22

https://github.com/rsevil/Transactions/blob/8125415d5a74eb129d2d0311762362dfa2679193/src/ChinhDo.Transactions.FileManager/Utils/FileUtils.cs#L8-L20

As far as I know, there is nothing that would stop that call from succeeding, since you would always have access to your own Appdata\Local\Temp folder. Maybe one of those Windows Defender type things?

You could try creating the folder yourself in Windows Explorer:

1. Open C:\Users\name\Appdata\Local\Temp
2. Ctrl-shift-N to make a new directory
3. Type CdFileMgr to set the name
4. Press enter

**Comment by GargamelKSP** [comment]
Even after creating the folder previously, I added 2 new mods today, and it threw this error again.  Manually adding the folder fixed it, again.  Adding and removing previously cached/installed mods did not trigger this error.

**Comment by HebaruSan** [comment]
Thanks, @GargamelKSP, that's a helpful clue. It means that something is _deleting_ the folder, not just failing to create it.

Can you please check whether you have this "Storage Sense" thing turned on, and/or "Delete temporary files that my apps aren't using"? Maybe Windows 10 is deleting it in a scheduled background task:

- https://winaero.com/blog/clear-temporary-files-automatically-windows-10/

**Comment by GargamelKSP** [comment]
Nope, had to check, but it's turned off.

**Comment by GargamelKSP** [comment]
Downloading and installing new mods while CKAN is still open from a manual fix earlier, error is not thrown.

**Comment by GargamelKSP** [comment]
Closing Ckan, reopening it, and DL and installing new mods also did not throw an error this time.   Previous (second) error was after a reboot.  
If you need any other testing, ask.

**Comment by drewcocker** [comment]
Running CKAN in administrator mode fixes this for me.

**Comment by politas** [comment]
>Running CKAN in administrator mode fixes this for me.

Why would you do that? Do you not care about your PC becoming part of some bot army, using up all your CPU resources?

**Comment by linuxgurugamer** [comment]
I haven't looked at the code that much, but:

It only checks to see if the folder is there when the TxFileManager is created.  But this happens hours after it was created.  I'm guessing that it creates it when you first go to the web, and relies on it being there for the duration of the session

**Comment by HebaruSan** [comment]
Good call, so maybe we can work around this by changing how and when we create `TxFileManager` objects. A search turns up several that are `private static readonly`, which should possibly be shorter-lived and only created as needed...

**Comment by linuxgurugamer** [comment]
I'll leave it in your hands

**Comment by linuxgurugamer** [comment]
Suffice to say, I would really like to see this fixed.  It's very annoying to have to close and reopen CKAN every few hours
