### ISSUE TITLE
module AGExt is not installed

### ISSUE THREAD

**Issue by Commissar0617** [KSP-CKAN/CKAN#2439]
win 8.1 pro. fresh upgraded install (autoupdater was borked)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CKAN.ModNotInstalledKraken: Module AGExt is not installed!
   at CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by Commissar0617** [comment]
may be due to my needing to delete the registry.json file in order to get ckan to work. everythign shows as autodetected. wish i could switch everything back to being managed by ckan

**Comment by HebaruSan** [comment]
We need to know what you were doing when this happened. Please fill in the questions in the issue template.
