### ISSUE TITLE
Error when launching ckan

### ISSUE THREAD

**Issue by kevanacker** [KSP-CKAN/CKAN#2448]
Background
----------

**CKAN Version:** 
1.25.0

**KSP Version:** 
1.4.3.2152

**Operating System:** 
Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
I double clicked the .exe (which is placed on the same drive as KSP)

**What did you expect to happen?**
Launching ckan

**What happened instead?**
I got an error that read:

Unhandled exception:
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'installed_files['GameData/CommunityResourcePack/ResourceConfigs/Hydrates.cfg']', line 631420, position 23.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CKAN.RegistryManager.Load()
   at CKAN.RegistryManager.LoadOrCreate()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args) 

**Screenshots:**

![image](https://user-images.githubusercontent.com/38056737/40150025-202e74a0-592c-11e8-9ba7-c2f94140ebcd.png)

**CKAN error codes (if applicable):** 
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'installed_files['GameData/CommunityResourcePack/ResourceConfigs/Hydrates.cfg']', line 631420, position 23.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CKAN.RegistryManager.Load()
   at CKAN.RegistryManager.LoadOrCreate()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by HebaruSan** [comment]
Looks like your `KSP\CKAN\registry.json` file got corrupted. Can you upload it to a paste-bin site somewhere and post the link?
