### ISSUE TITLE
Unhandled Exception: illegal characters in path

### ISSUE THREAD

**Issue by ErrorSys** [KSP-CKAN/CKAN#2467]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.4.2215

**Operating System:** 
Windows 10 Home

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
I selected about 60 mods from the compatible list and then selected apply, then CKAN proceeds to Download the mods.

**What did you expect to happen?**
Clean download and install of selected mods.

**What happened instead?**
Threw an Unhandled Exception when finished downloading.

**Screenshots:**

![image](https://user-images.githubusercontent.com/38744863/42255660-0ec5581a-7f0a-11e8-8b84-d6a87ea6ecd4.png)

**CKAN error codes (if applicable):** 
```
Unhandled exception:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at ICSharpCode.SharpZipLib.Zip.ZipEntry.CleanName(String name)
   at ICSharpCode.SharpZipLib.Zip.ZipEntry..ctor(String name, Int32 versionRequiredToExtract, Int32 madeByInfo, CompressionMethod method)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at CKAN.NetFileCache.ZipValid(String filename, String& invalidReason)
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)
   at CKAN.NetAsyncModulesDownloader.<>c__DisplayClass8_0.<DownloadModules>b__3(Uri[] _uris, String[] paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.triggerCompleted(Uri[] file_urls, String[] file_paths, Exception[] errors)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

**Comment by HebaruSan** [comment]
Looks like a problem with one of the ZIP files. Are you able to install these mods individually?

**Comment by ErrorSys** [comment]
Unfortunately, I am not. I have tried many times however im not able to get mods to work together, and I resorted to using CKAN. How would I go about finding which zip file is causing the issue? I might be able to  fix that.

**Comment by HebaruSan** [comment]
Oh, I meant to try installing a smaller selection of mods, but still using CKAN, until you find one that causes this error by itself. If we knew which mod it was, we could look at the file to see what's wrong.

**Comment by ErrorSys** [comment]
Found which one was causing the problem. Flag Pack by willwill2will54 version 1.1
Installed each of my selected mods and that one was the only one that caused the Unhandled Exception.

**Comment by HebaruSan** [comment]
Nice! I get many errors like this trying to unzip that file manually in Windows:

![image](https://user-images.githubusercontent.com/1559108/42302138-d9076fd8-8008-11e8-8621-aea052b685ad.png)

Possibly because of the quotes in the filename? There's also a `__MACOSX` folder in that ZIP, so I think we can guess how this happened.

I've submitted two issues to that mod's repo, linked above; hopefully he'll fix it.

**Comment by ErrorSys** [comment]
Anyways, I don't know if there are other mods that have this problem. I would check all of them but I just don't have that kind of time or patients to do so. I hope I have helped in resolving this issue.

**Comment by willwill2will54** [comment]
@ErrorSys Fixed in the new version of my mod. Sorry for any inconvenience caused.

**Comment by HebaruSan** [comment]
Confirmed that the latest version is indexed and installable on Windows. Thanks for the fix!
