### ISSUE TITLE
The Comprehensive Kerbal Archive Network (CKAN) dosent work at all. 

### ISSUE THREAD

**Issue by BobTheKerbal** [KSP-CKAN/CKAN#2566]
_oof I got a problem someone help_

Background
----------

**CKAN Version:1.2.5.3 

**KSP Version:**1.3.1 

**Operating System:**Windows 10 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** downloading mods manually since CKAN stopped working

Problem
-------

**What steps did you take in CKAN? I downloaded the program like anyone else would.

**What did you expect to happen?** The screen to download mods to show up. 

**What happened instead?** I got a big black screen with white letters saying the following: Unhandled exception:
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'installed_files['GameData/000_FilterExtensions/Icons/Autoloaded_PatchIcon/EngineMethane_selected.dds']', line 727159, position 36.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CKAN.RegistryManager.Load()
   at CKAN.RegistryManager.LoadOrCreate()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, KSPManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, KSPManager manager)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args) 

**Screenshots:**

https://imgur.com/a/pHAF8Sk

**Comment by HebaruSan** [comment]
Your registry got corrupted. If you don't have any information about how it happened, the best we can do is advise you to delete it to start over.

1. Open your KSP folder
2. Open the CKAN folder
3. Delete `registry.json`

All your installed mods will switch to "AD"; this is unavoidable because the data is gone. You may wish to reset your GameData to a stock-only state and re-install mods.

**Comment by BobTheKerbal** [comment]
So It is mandatory to delete _everything?_

**Comment by HebaruSan** [comment]
I don't know what you mean by "everything". I specified the exact file to delete.
