### ISSUE TITLE
Can't install and unistall mods

### ISSUE THREAD

**Issue by Owlverlord** [KSP-CKAN/CKAN#2575]
Background
----------

**CKAN Version:** 
1.25.3

**KSP Version:** 
1.5.1.2335

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
tried to install/uninstall mods

**What did you expect to happen?**
not getting an error

**What happened instead?**
i got an error message and can't save changes

**Screenshots:**

![image](https://user-images.githubusercontent.com/45040742/48491196-4b548900-e827-11e8-9f96-e9fc20980a44.png)

I'm going to copy the error log here:
************** Exception Text **************
CKAN.DependencyNotSatisfiedKraken: Exception of type 'CKAN.DependencyNotSatisfiedKraken' was thrown.
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>d__242.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**CKAN error codes (if applicable):** 
CKAN.DpendencyNotSatisfiedKraken

**Comment by HebaruSan** [comment]
Need to know which mods you have installed and which you're trying to install.

**Comment by Owlverlord** [comment]
It doesn't matter which mods I'm trying to install/uninstall I get the error every time.
but here are the mods I have currently installed 
![image](https://user-images.githubusercontent.com/45040742/48491868-d41ff480-e828-11e8-9443-3dc61a2a132c.png)

**Comment by Owlverlord** [comment]
I have no real idea how but I've fixed it.
