### ISSUE TITLE
`ckan ksp fake` crashes with no arguments

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2637]
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake`

See #2627 for background on this command.

**What did you expect to happen?**

Print help about how to use the subcommand

**What happened instead?**

NRE

**CKAN error codes (if applicable):** 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
   at CKAN.CmdLine.KSP.<>c__DisplayClass9_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.KSP.RunSubCommand(KSPManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
Segmentation fault
```

**Comment by HebaruSan** [comment]
It crashes even if you leave off *one* argument (the last one being the DLC version), as in

`ckan ksp fake FAKETEST4 fake4 1.6.0`

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
   at CKAN.CmdLine.KSP.<>c__DisplayClass9_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.KSP.RunSubCommand(KSPManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
Segmentation fault
```

**Comment by DasSkelett** [comment]
Thanks for r the tests and reports :+1: 
I thought that in my tests it DID print the usage message, but it seems I'm wrong.
Going to fix those.
