### ISSUE TITLE
`ckan ksp clone` crashes with no arguments

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2638]
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp clone`

See #2627 for background on this command.

**What did you expect to happen?**

Print help about how to use the subcommand

**What happened instead?**

`ArgumentNullException`

**CKAN error codes (if applicable):** 
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.SortedList`2.IndexOfKey(TKey key)
   at System.Collections.Generic.SortedList`2.ContainsKey(TKey key)
   at CKAN.KSPManager.HasInstance(String name)
   at CKAN.CmdLine.KSP.CloneInstall(CloneOptions options)
   at CKAN.CmdLine.KSP.<>c__DisplayClass9_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.KSP.RunSubCommand(KSPManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
Same thing happens if even one argument is missing (in this case the new path):

`ckan ksp clone fake1 FAKETEST5`

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.CreateDirectory(String path)
   at CKAN.Utilities._CopyDirectory(String sourceDirPath, String destDirPath, Boolean copySubDirs)
   at CKAN.Utilities.CopyDirectory(String sourceDirPath, String destDirPath, Boolean copySubDirs)
   at CKAN.KSPManager.CloneInstance(KSP existing_instance, String new_name, String new_path)
   at CKAN.CmdLine.KSP.CloneInstall(CloneOptions options)
   at CKAN.CmdLine.KSP.<>c__DisplayClass9_0.<RunSubCommand>b__0(String option, Object suboptions)
   at CommandLine.Parser.ParseArgumentsStrict(String[] args, Object options, Action`2 onVerbCommand, Action onFail)
   at CKAN.CmdLine.KSP.RunSubCommand(KSPManager manager, CommonOptions opts, SubCommandOptions unparsed)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```
