### ISSUE TITLE
NullReferenceException in `_updateFilters()` on Windows

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2650]
Background
----------

**CKAN Version:** 
Current master (5434adb8cc9c73d5c599de1d0a33ec6ee2a768ca)
and earlier

**KSP Version:** 
1.6.0

**Operating System:** 
Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**
Start it.

**What did you expect to happen?**
It should start without errors.

**What happened instead?**
Unhandled NullReferenceException is thrown.

**CKAN error codes (if applicable):** 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Main._UpdateFilters()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.UpdateFilters(Main control)
   at CKAN.Main.<.ctor>b__37_0(MainModList source)
   at CKAN.MainModList.set_ModFilter(GUIModFilter value)
   at CKAN.Main.Filter(GUIModFilter filter)
   at CKAN.Main.CurrentInstanceUpdated()
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

@politas already mentioned it earlier [here](https://github.com/KSP-CKAN/CKAN/pull/2619#issuecomment-449918965).

**Comment by DasSkelett** [comment]
It's somewhere in here:
https://github.com/KSP-CKAN/CKAN/blob/5434adb8cc9c73d5c599de1d0a33ec6ee2a768ca/GUI/MainModList.cs#L100-L140
But the only change in the near past was https://github.com/KSP-CKAN/CKAN/commit/01c9cf12e47fff428bee587b4f8eb7eda12349b8, and that's purely visual changes.

**Comment by HebaruSan** [comment]
I think this is a threading thing related to #2617.

**Comment by DasSkelett** [comment]
Yeah it actually throws on line 109. I think `_UpdateFilters()` is called before `_UpdateModsList()` has completed.

**Comment by DasSkelett** [comment]
`mainModList.full_list_of_mod_rows` only gets set in `mainModList.ConstructModList()`.
`mainModList.ConstructModList()` is only called in `_UpdateModsList()`.
And that one seems to be to slow on some systems, so that `_UpdateFilters()` tries to access `mainModList.full_list_of_mod_rows` before it is set.

**Comment by HebaruSan** [comment]
A simple null check might suffice, since `UpdateModsList` calls `UpdateFilters` at the end.

**Comment by DasSkelett** [comment]
But what about the `FilterToolButton.Text`?

**Comment by HebaruSan** [comment]
I'm adding the null check to `UpdateFilters`, not `Filter`, so it'll be set regardless.

**Comment by DasSkelett** [comment]
Welp, yeah, not my brightest moment.
