### ISSUE TITLE
Fake/clone tests fail on Windows

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2752]
Background
----------

**CKAN Version:** 
1.26.0

**Operating System:** 
Windows 7

Problem
-------

**What steps did you take in CKAN?**
```
.\build.ps1 test
```

**What did you expect to happen?**
All tests pass

**What happened instead?**
```
1) Error : Tests.Core.KSPManagerTests.CloneInstance_ToNotEmptyFolder_ThrowsIOException
System.IO.IOException : The process cannot access the file 'shouldntbehere.txt' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Tests.Core.KSPManagerTests.CloneInstance_ToNotEmptyFolder_ThrowsIOException() in C:\Users\Paul\github\CKAN\Tests\Core\KSPManager.cs:line 144

2) Error : Tests.Core.KSPManagerTests.FakeInstance_InNotEmptyFolder_ThrowsBadInstallLocationKraken
System.IO.IOException : The process cannot access the file 'shouldntbehere.txt' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Tests.Core.KSPManagerTests.FakeInstance_InNotEmptyFolder_ThrowsBadInstallLocationKraken() in C:\Users\Paul\github\CKAN\Tests\Core\KSPManager.cs:line 194

3) Error : Tests.Core.KSPManagerTests.FakeInstance_ValidArgumentsWithDLC_ManagerHasValidInstance
System.IO.IOException : The process cannot access the file 'registry.locked' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Tests.Core.KSPManagerTests.FakeInstance_ValidArgumentsWithDLC_ManagerHasValidInstance() in C:\Users\Paul\github\CKAN\Tests\Core\KSPManager.cs:line 214
```

**Comment by DasSkelett** [comment]
On Linux they pass:
```
Test Run Summary
Overall result: Passed
Test Count: 682, Passed: 677, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 5                                                             
Skipped Tests - Ignored: 0, Explicit: 5, Other: 0                                                                                           
Start time: 2019-05-05 23:58:31Z                                                                                                              
End time: 2019-05-05 23:58:44Z                                                                                                              
Duration: 12.178 seconds       
```
So somehow Windows keeps files locked after they are created, for some time?

**Comment by HebaruSan** [comment]
Or, as a wise man once said...

https://github.com/KSP-CKAN/CKAN/blob/df8fb70fc054a488409e2d04915fe6719b1ea128/quotes.txt#L11-L16

**Comment by Nerfclasher** [comment]
almost the same issue 
[New Text Document.txt](https://github.com/KSP-CKAN/CKAN/files/3259722/New.Text.Document.txt)

**Comment by HebaruSan** [comment]
@Nerfclasher, that's unrelated. Your KSP/CKAN/registry.json file is corrupted (possibly a problem with the disk, not sure how else a CRC would come into loading a simple text file).
https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process
