### ISSUE TITLE
On Launch >> Unhandled Exception: System.IO.IOException: The device is not ready.

### ISSUE THREAD

**Issue by Kinisson** [KSP-CKAN/CKAN#3076]
Background
----------
*  WIN 10
* CKAN v1.27.2
* KSP Version: 1.9.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
ckan doesn't open GUI and show error as posted
Last version running without this error is: v1.26.2

**Steps to reproduce**
launch app

**Expected behavior**
--

**Screenshots (if applicable)**
--
**CKAN error code (if applicable):**

Unhandled Exception: System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at CKAN.KSPManager.LoadInstancesFromRegistry()
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by HebaruSan** [comment]
Is your KSP folder on a read-only device, like a DVD-ROM or some kind of network filesystem? That's what comes up when I search for that error.

**Comment by Kinisson** [comment]
Hi!
Not really. It's a Steam installation on a SSD.
As I said I can run the version v1.26.2. 
Something changed after this version, since the CKAN file is half the size since then.
I get the error either KSP is installed or not, and also if running from any of my drives

But don't worry too much , since I can use v1.26.2.

**Comment by Kinisson** [comment]
Found the problem!
config.json cache folder was corrupted !
Deleted it and it runs ok :)
