### ISSUE TITLE
[Bug] Crash due to Configuration?

### ISSUE THREAD

**Issue by CertifiedChewie** [KSP-CKAN/CKAN#3124]
Background
----------
* Operating System: Windows 10
* CKAN Version: 
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

No

Problem
-------
Command promt screen, then error CKAN has stopped working

A CMD promt which reads:

```
382 [1] WARN CKAN.Configuration.Win32RegistryConfiguration (null) - Could not parse cached build map

Unhandled Exception: Autofac.Core.DependencyResolutionException: An exception was thrown while activating CKAN.Configuration.JsonConfiguration.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'JsonConfiguration'.
 ---> System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
   at Newtonsoft.Json.Utilities.EnumUtils.InitializeValuesAndNames(StructMultiKey`2 key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.EnumUtils.GetEnumValuesAndNames(Type enumType)
   at Newtonsoft.Json.JsonWriter.BuildStateArray()
   at Newtonsoft.Json.JsonWriter..cctor()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonWriter..ctor()
   at Newtonsoft.Json.JsonTextWriter..ctor(TextWriter textWriter)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at CKAN.Configuration.JsonConfiguration.SaveConfig()
   at CKAN.Configuration.JsonConfiguration.Migrate()
   at CKAN.Configuration.JsonConfiguration.LoadConfig()
   at CKAN.Configuration.JsonConfiguration..ctor()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass6_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
Looks like your .NET installation is corrupted somehow. You should have a copy of `System.Runtime.Serialization`.
