### ISSUE TITLE
[Bug] When installing RSS-16k Textures, System.IO.IOException: The process cannot access the file 'c:\program files (x86)\steam\SteamApps\common\Kerbal Space Program\GameData\RSS-Textures\EarthColor.dds' because it is being used by another process

### ISSUE THREAD

**Issue by joey-lg** [KSP-CKAN/CKAN#3227]
Background
----------
* Operating System: Windows 10 Home Build 18362
* CKAN Version: 1.29.2
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
An Error window appears with this message 
"Unhandled exception:
System.Transactions.TransactionException: Failed to roll back. ---> System.IO.IOException: The process cannot access the file 'c:\program files (x86)\steam\SteamApps\common\Kerbal Space Program\GameData\RSS-Textures\EarthColor.dds' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at ChinhDo.Transactions.FileManager.Operations.SingleFileOperation.Rollback()
   at ChinhDo.Transactions.FileManager.TxEnlistment.Rollback(Enlistment enlistment)
   --- End of inner exception stack trace ---
   at ChinhDo.Transactions.FileManager.TxEnlistment.Rollback(Enlistment enlistment)
   at System.Transactions.VolatileEnlistmentAborting.EnterState(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateAborted.EnterState(InternalTransaction tx)
   at System.Transactions.EnlistableStates.Timeout(InternalTransaction tx)
   at System.Transactions.Bucket.TimeoutTransactions()
   at System.Transactions.BucketSet.TimeoutTransactions()
   at System.Transactions.TransactionTable.ThreadTimer(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers() 

**Steps to reproduce**
* Go to... CKAN
* Click on... Real Solar System Textures 16k pixels and apply changes.
* See error

**Expected behavior**
It should install the mod.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Is the game still running?

**Comment by HebaruSan** [comment]
... worked fine for me, for what it's worth.

![image](https://user-images.githubusercontent.com/1559108/101268945-fdd64c00-3760-11eb-9f69-1ba204b5d2b6.png)
