### ISSUE TITLE
Uhhh... It's not working. Not sure if this info helps but this is what I get.

### ISSUE THREAD

**Issue by PropaineX** [KSP-CKAN/CKAN#3247]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.ManageMods.MarkAllUpdates()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment]
We need to know what your setup is like and what you're doing. That's why we created this issue template:

- https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Please fill it out.
