### ISSUE TITLE
[Bug] Installing mods through audit recommendations causes error

### ISSUE THREAD

**Issue by Jesscah03** [KSP-CKAN/CKAN#3291]
Background
----------
* Operating System: Windows 10 64x
* CKAN Version: 1.29.2
* KSP Version: 1.11

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I downloaded Stockalike Station Parts Expansion Redux and Coatl Areospace, aka ProbesPlus

Problem
-------
**Describe the bug**
When installing a mod through the audit recommendations menu a error window shows up (see screenshot) the error seems random like it will install and audited mod fine but other times it just brings up the error before the install begins

**Steps to reproduce**
* Go to audit recommendations
* Click on modular rocket systems (thats the mod that specifically isnt working for me notably when installing normally through it installs as expected)
* See error

**Expected behavior**
an error as shown in the screenshots should appear

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/78704479/107159502-1d067b00-6956-11eb-9cbe-66a7bd6a74eb.png)
specific image from my ro rp-1 install when installing near future solar

**CKAN error code (if applicable):**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Already contains module: NSSC
   at CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.ChooseRecommendedMods.FindConflicts()
   at CKAN.ChooseRecommendedMods.MarkConflicts()
   at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked(Object sender, ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Jesscah03** [comment]
update: I get the same error as seen below when after trying to install bon voyage through the normal ckan mod browser
![image](https://user-images.githubusercontent.com/78704479/107160608-e54f0180-695c-11eb-8568-055887bf67b3.png)

**Comment by HebaruSan** [comment]
Thanks for the report. The audit recommendations screen is driven by your installed mods, so we'll need to know what those are to investigate this. Can you please add them to the description (or a comment)?

**Comment by Jesscah03** [comment]
[JModlist.txt](https://github.com/KSP-CKAN/CKAN/files/5940293/JModlist.txt)
mod list provided by ckan and Stockalike Station Parts Expansion Redux and Coatl Areospace, aka ProbesPlus installed manually i also have both dlcs installed

**Comment by HebaruSan** [comment]
Thanks! I just finished installing all of those, and I can select ModularRocketSystems in the audit recommendations list with no errors. Is there any other part of this that we should be aware of?

**Comment by HebaruSan** [comment]
This feels slightly related to #3161, even if only distantly—weird corruption relating to the install flow. Fingers crossed that we can fix two with one change.

**Comment by HebaruSan** [comment]
A modpack export in case anyone wants a quicker way to catch up:

- [Jesscah03.zip](https://github.com/KSP-CKAN/CKAN/files/5940449/Jesscah03.zip)

**Comment by Jesscah03** [comment]
![image](https://user-images.githubusercontent.com/78704479/107163512-7a5af600-696f-11eb-9f37-db069ecddbef.png)
I got the error again after doing some more testing i installed science alert realerted through audit recommendations that worked fine than i uninstalled it worked fine aswell than i clicked audit recommendations and it gave me this error

**Comment by HebaruSan** [comment]
- What does audit recommendations look like when you open it?
  - Are the checkboxes as they should be (recommendations checked, everything else unchecked)?
- Are you clicking this checkbox at the bottom left at all?
  ![image](https://user-images.githubusercontent.com/1559108/107163638-56e47b00-6970-11eb-9667-3b32d4db611a.png)
  It seems to be key to at least the bugs I'm observing. When I uncheck it, there's some funny business around the timing of how the code re-checks it and repopulates the grid on the next launch.

**Comment by HebaruSan** [comment]
The NSSC message is really interesting. "Adding NSSC twice in relationship resolution"—I think this is because NSSC and NotSoSimpleConstruction both provide NSSC, which confuses some logic or other when both are checked, which would happen due to the checkbox funny business noted above.

**Comment by Jesscah03** [comment]
![image](https://user-images.githubusercontent.com/78704479/107163814-3ec12b80-6971-11eb-8532-ca59823494a4.png)
this is my audit recommendations when i press it i than click the deselect button something just noticed is this
![image](https://user-images.githubusercontent.com/78704479/107163853-8051d680-6971-11eb-8865-ebf1760d9c94.png)
why is there two of them?

**Comment by HebaruSan** [comment]
We got a duplicate request to index that mod in KSP-CKAN/NetKAN#6202 after it was already indexed in KSP-CKAN/NetKAN#4968 and didn't recognize it was a duplicate at first, see KSP-CKAN/NetKAN#7688 for details.

**Comment by HebaruSan** [comment]
Awesome; just opening that screen, unchecking everything, and checking NSSC and NotSoSimpleConstruction gives me a hard crash:

```
28701 [1] ERROR CKAN.RelationshipResolver (null) - Assertion failed: Adding NSSC twice in relationship resolution
System.ArgumentException: Already contains module: NSSC
  at CKAN.RelationshipResolver.Add (CKAN.CkanModule module, CKAN.SelectionReason reason) [0x0007b] in <6a47e5b996604b7ea227275020b13b34>:0 
  at CKAN.RelationshipResolver.AddModulesToInstall (System.Collections.Generic.IEnumerable`1[T] modules) [0x00144] in <6a47e5b996604b7ea227275020b13b34>:0 
  at CKAN.RelationshipResolver..ctor (System.Collections.Generic.IEnumerable`1[T] modulesToInstall, System.Collections.Generic.IEnumerable`1[T] modulesToRemove, CKAN.RelationshipResolverOptions options, CKAN.IRegistryQuerier registry, CKAN.Versioning.GameVersionCriteria GameVersion) [0x00028] in <6a47e5b996604b7ea227275020b13b34>:0 
  at CKAN.ChooseRecommendedMods.FindConflicts () [0x0003a] in <6a47e5b996604b7ea227275020b13b34>:0 
  at CKAN.ChooseRecommendedMods.MarkConflicts () [0x00001] in <6a47e5b996604b7ea227275020b13b34>:0 
  at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked (System.Object sender, System.Windows.Forms.ItemCheckedEventArgs e) [0x00045] in <6a47e5b996604b7ea227275020b13b34>:0 
  at System.Windows.Forms.ListView.OnItemChecked (System.Windows.Forms.ItemCheckedEventArgs e) [0x00019] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.ListViewItem.set_Checked (System.Boolean value) [0x0006c] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.ListView+ItemControl.ItemsMouseDown (System.Object sender, System.Windows.Forms.MouseEventArgs me) [0x000dd] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.Control.OnMouseDown (System.Windows.Forms.MouseEventArgs e) [0x00019] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.Control.WmLButtonDown (System.Windows.Forms.Message& m) [0x0008b] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001bc] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.ListView+ItemControl.WndProc (System.Windows.Forms.Message& m) [0x00071] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <a0f8b82443494dec9b517126f4032efe>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <a0f8b82443494dec9b517126f4032efe>:0 
```

**Comment by HebaruSan** [comment]
These two blocks disagree vehemently regarding the seriousness of duplicates in `modlist`:

https://github.com/KSP-CKAN/CKAN/blob/ae3dd4443cf6d693896565aa3bc0aa1ad3e71b41/Core/Relationships/RelationshipResolver.cs#L537-L542

https://github.com/KSP-CKAN/CKAN/blob/ae3dd4443cf6d693896565aa3bc0aa1ad3e71b41/Core/Relationships/RelationshipResolver.cs#L559-L566

So...

1. NotSoSimpleConstruction gets added to the relationship resolver first
2. Its `provides` list contains `NSSC`, so that gets added to `modlist` as well
3. Later, the original NSSC gets added, which the resolver doesn't like
