### ISSUE TITLE
[Bug] Possibly a new zip lib problem

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#3348]
## Background

* Operating System: Win7
* CKAN Version: 1.30.1 (dev compile)
* KSP Version: 1.11.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Kind of, see description

## Problem

**Steps to reproduce**

1. Install PlanningNode with CKAN
2. Exit CKAN
3. Manually edit `registry.json` to remove the PlanningNode entry from `installed_modules`, so it will be detected as manually installed
4. Run ConsoleUI and note that PlanningNode shows up as upgradeable
5. Try to upgrade it
6. During the install flow, an uncaught `System.NotSupportedException` is thrown by SharpZipLib

**Expected behavior**

Install the module over the "manually installed" copy.

Upgrading manually installed modules might be broken.

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/1559108/114913389-aa5fc300-9e10-11eb-9d14-9fb5060fa72d.png)

**CKAN error code (if applicable):**

```
Unhandled Exception: System.NotSupportedException: InflaterInputStream Length is not supported
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.get_Length()
   at CKAN.ModuleInstaller.StreamsEqual(Stream s1, Stream s2)
   at CKAN.ModuleInstaller.<FindConflictingFiles>d__21.MoveNext()
   at CKAN.Extensions.Memoized`1.TryGetItem(Int32 index, T& item)
   at CKAN.Extensions.Memoized`1.<GetMemoizingEnumerator>d__3.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at CKAN.ModuleInstaller.InstallModule(CkanModule module, String zip_filename, Registry registry, HashSet`1& possibleConfigOnlyDirs)
   at CKAN.ModuleInstaller.Install(CkanModule module, Boolean autoInstalled, Registry registry, HashSet`1& possibleConfigOnlyDirs, String filename)
   at CKAN.ModuleInstaller.AddRemove(HashSet`1& possibleConfigOnlyDirs, RegistryManager registry_manager, IEnumerable`1 add, IEnumerable`1 remove, Boolean enforceConsistency)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, IDownloader netAsyncDownloader, HashSet`1& possibleConfigOnlyDirs, RegistryManager registry_manager, Boolean enforceConsistency, Boolean resolveRelationships, Boolean ConfirmPrompt)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, IDownloader netAsyncDownloader, HashSet`1& possibleConfigOnlyDirs, RegistryManager registry_manager, Boolean enforceConsistency)
   at CKAN.ConsoleUI.InstallScreen.Run(ConsoleTheme theme, Action`1 process)
   at CKAN.ConsoleUI.Toolkit.ConsoleScreen.LaunchSubScreen(ConsoleTheme theme, ConsoleScreen cs, Action`1 newProc)
   at CKAN.ConsoleUI.ModListScreen.ApplyChanges(ConsoleTheme theme)
   at CKAN.ConsoleUI.ModListScreen.<.ctor>b__0_26(Object sender, ConsoleTheme theme)
   at CKAN.ConsoleUI.Toolkit.ScreenContainer.Interact(ConsoleTheme theme)
   at CKAN.ConsoleUI.Toolkit.ScreenContainer.Run(ConsoleTheme theme, Action`1 process)
   at CKAN.ConsoleUI.ConsoleCKAN..ctor(GameInstanceManager mgr, String themeName, Boolean debug)
   at CKAN.ConsoleUI.ConsoleUI.Main_(String[] args, GameInstanceManager manager, String themeName, Boolean debug)
   at CKAN.CmdLine.MainClass.ConsoleUi(GameInstanceManager manager, ConsoleUIOptions opts, String[]args)
   at CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, GameInstanceManager manager)
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
Here's where we innocently attempt to get the length of a zip stream.

https://github.com/KSP-CKAN/CKAN/blob/454e1deb72f74d294c59a3e885a89b46b3113525/Core/ModuleInstaller.cs#L461

I have to guess that this was one of the changes in the version SharpZipLib to which we recently upgraded, because this code got a lot of exercise while upgrading of manually installed modules was being developed.

**Comment by DasSkelett** [comment]
https://github.com/icsharpcode/SharpZipLib/blame/7ed87d10b8ecafeb5abb5a129c046837416ac11f/src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/InflaterInputStream.cs#L534-L544

This seems to be the culprit:
https://github.com/icsharpcode/SharpZipLib/pull/84

Sounds like we aren't supposed to try to get the size of the zip stream.

**Comment by HebaruSan** [comment]
If I switch these parameters, it works, because we can still check the size of the file on disk:

https://github.com/KSP-CKAN/CKAN/blob/454e1deb72f74d294c59a3e885a89b46b3113525/Core/ModuleInstaller.cs#L441

**Comment by DasSkelett** [comment]
Makes sense. If we want to keep `StreamsEqual()`generic, we should probably switch out that for loop with a while that breaks if there is no more data (`bytesFrom1 != bytesFrom2 && ( bytesFrom1 == 0 || bytesFrom2 == 0)` ?)

The behavior kind of makes sense, given the nature of streams you don't always know the size of them ahead of time.

**Comment by HebaruSan** [comment]
> The behavior kind of makes sense, given the nature of streams you don't always know the size of them ahead of time.

Then they shouldn't have `Length` properties. :frowning_face:

**Comment by DasSkelett** [comment]
It's C#, just throw an exception and now it's your caller's problem, with some luck it's not in your responsibility anymore ^^
