### ISSUE TITLE
UnauthorizedAccessException while trying to store file in cache

### ISSUE THREAD

**Issue by frozen001** [KSP-CKAN/CKAN#3388]
Background
----------
* Operating System: windows 10 
* CKAN Version: 1.30.4
* KSP Version: 1.11.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
after the new update it crashes every time tries to download anything

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**
```
Unhandled exception:
System.UnauthorizedAccessException: Access to the path 'D:\Downloads\ckandownloads\22A8E3D1-ClickThroughBlocker-1-0.1.10.15.zip' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at ChinhDo.Transactions.FileManager.TxFileManager.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at CKAN.NetFileCache.Store(Uri url, String path, String description, Boolean move)
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at CKAN.NetAsyncDownloader.NetAsyncDownloaderDownloadPart.<ResetAgent>b__20_1(Object sender, AsyncCompletedEventArgs args)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

**Comment by DasSkelett** [comment]
Did you do anything else before/after updating CKAN? Like changing the cache location, or manipulating the permission settings of the directory?

CKAN seems to not be allowed to access your custom cache path anymore. You could try deleting the folder `D:\Downloads\ckandownloads\` and recreating it, or resetting the cache path to the default on in the CKAN settings.

**Comment by HebaruSan** [comment]
> access your custom cache path

Might be the transaction library's path:

> ```
>    at ChinhDo.Transactions.FileManager.TxFileManager.Copy(String sourceFileName, String destFileName, Boolean overwrite)
> ```

I know it's `/tmp/CdFileMgr` (????) on Linux, any idea what it uses on Windows?
