### ISSUE TITLE
[Bug] Unhandled exception on startup: Could not load 'System.EnterpriseServices.Wrapper.dll'

### ISSUE THREAD

**Issue by pl4sma2389** [KSP-CKAN/CKAN#3430]
Background
----------
* Operating System: Win10 Home x64
* CKAN Version: 1.30.4
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes

Problem
-------
**Describe the bug**
On startup, CKAN doesn't fully load and displays the error message in the screenshot. Clicking continue gets CKAN to the state in the second screenshot. CKAN then behaves very erratically; when clicking "Add available updates" it displays the message in the third screenshot; when clicking refresh, it shows the image in the fourth screenshot and then CKAN is in the state of the fifth screenshot with outdated mod information.

It's been doing this for a very long time. Deleting and redownloading CKAN doesn't fix it.

**Steps to reproduce**
* Start CKAN.
* See error.

**Expected behavior**
* Start CKAN.
* Don't see error.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/68903981/128322351-742a450d-e8c4-4dfc-a761-e8e1d8f9079c.png)
![image](https://user-images.githubusercontent.com/68903981/128322554-58dbd061-2d0c-4ca0-b199-f3a70feeef7e.png)
![image](https://user-images.githubusercontent.com/68903981/128322690-a97f3136-c790-44ab-94f6-55fc9564bd08.png)
![image](https://user-images.githubusercontent.com/68903981/128322802-79928244-8e71-4d44-a540-bc532482e3b7.png)
![image](https://user-images.githubusercontent.com/68903981/128322897-7c4489fb-cd51-46c1-b0b4-44f7ad8d36a1.png)

**CKAN error code (if applicable):**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'System.EnterpriseServices.Wrapper.dll' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'System.EnterpriseServices.Wrapper.dll' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'System.EnterpriseServices.Wrapper.dll'




   at System.Transactions.Transaction.JitSafeGetContextTransaction(ContextData contextData)
   at System.Transactions.Transaction.FastGetTransaction(TransactionScope currentScope, ContextData contextData, Transaction& contextTransaction)
   at System.Transactions.Transaction.GetCurrentTransactionAndScope(TxLookup defaultLookup, Transaction& current, TransactionScope& currentScope, Transaction& contextTransaction)
   at System.Transactions.TransactionScope.CommonInitialize()
   at System.Transactions.TransactionScope.NeedToCreateTransaction(TransactionScopeOption scopeOption)
   at System.Transactions.TransactionScope..ctor(TransactionScopeOption scopeOption, TransactionOptions transactionOptions, TransactionScopeAsyncFlowOption asyncFlowOption)
   at CKAN.CkanTransaction.CreateTransactionScope()
   at CKAN.GameInstance.Scan()
   at CKAN.Main.CurrentInstanceUpdated(Boolean allowRepoUpdate)
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 1.30.0.0
    Win32 Version: 1.30.4
    CodeBase: file:///F:/FastLibrary/steamapps/common/Kerbal%20Space%20Program/ckan.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by DasSkelett** [comment]
Hm, I just had a look around, because I can't remember seeing this exception before, and the only mention of a similar error with `System.EnterpriseServices.Wrapper.dll` was in #1309. There the reporting user said it solved itself after a day.

This is a DLL that should come with the .NET Framework runtime. Maybe try reinstalling that.

**Comment by pl4sma2389** [comment]
Not resolved yet.

**Comment by DasSkelett** [comment]
You didn't respond anything in a week, that's why our not closed it.
Did you try what I suggested in my comment?
