### ISSUE TITLE
Transaction timeout during clone instance and mod install

### ISSUE THREAD

**Issue by MasterJack555** [KSP-CKAN/CKAN#3483]
So Im trying to add a new instance via the cloning option and keep getting this error about 50% into the cloning

So here is the code of the error:

```
Unhandled exception:
System.Transactions.TransactionException: Failed to roll back. ---> System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at ChinhDo.Transactions.FileManager.Operations.CreateDirectory.Rollback()
   at ChinhDo.Transactions.FileManager.TxEnlistment.Rollback(Enlistment enlistment)
   --- End of inner exception stack trace ---
   at ChinhDo.Transactions.FileManager.TxEnlistment.Rollback(Enlistment enlistment)
   at System.Transactions.VolatileEnlistmentAborting.EnterState(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateAborted.EnterState(InternalTransaction tx)
   at System.Transactions.EnlistableStates.Timeout(InternalTransaction tx)
   at System.Transactions.Bucket.TimeoutTransactions()
   at System.Transactions.BucketSet.TimeoutTransactions()
   at System.Transactions.TransactionTable.ThreadTimer(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers() 
```

After clicking "dismiss" on the error, it also dismisses CKAN, by which i mean CKAN shuts itself down completely.

**Comment by HebaruSan** [comment]
There are two problems to investigate here:

1. Why did the copy fail in the first place?
2. Why did the rollback fail?

We have zero clues about the first problem and only a slight hint about the second. If a directory wasn't empty during rollback, then I think that would mean that a file was somehow copied outside of the transaction framework, but I see nowhere in the code that might do that; all of the file copies are via the `TxFileManager` object:

https://github.com/KSP-CKAN/CKAN/blob/136c26dcf6bc74d5854c474c1012a51a084f0167/Core/Utilities.cs#L17-L82

@MasterJack555, the issue template asked about your OS because that can give us important clues about what's happening. Can you please fill that in?

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by HebaruSan** [comment]
This might be another problem caused by antivirus interference. If an antivirus service opened a file for reading, that could stop the rollback from deleting that file on Windows. But we would still need to explain why the copy operation failed in the first place.

**Comment by HebaruSan** [comment]
> 1. Why did the copy fail in the first place?

The transaction for installing the change set is timing out! I just had this happen during a test install of RP-1-ExpressInstall in ConsoleUI. Apparently somewhere in the transaction libraries that we're using, someone arbitrarily decided that no transction should ever last longer than... felt like 2–5 minutes or so? And it mistakenly thinks that CKAN has gone into an infinite loop, but in reality it's working fine. So we either need to increase the timeout, or somehow actively report back to the transaction library that we're still active and still OK so it resets the timeout counter.

This is the likely cause of all the previous times we've seen the same stack trace (see #3227, #3294, #3455). When I suggested people check their antivirus and try again, it probably had no effect other than speeding up the operations to install so they finished before the timeout was reached (e.g., by caching the downloads during the failed attempts).

> 2. Why did the rollback fail?

The transaction timeout apparently works by starting another background thread, which basically sleeps until the timout and then tries to roll back. This then tries to delete files that are still locked by the foreground thread that's in the middle of the install at that time, and the whole thing crashes.

**Comment by HebaruSan** [comment]
Since this background-thread method of timing out a transaction basically _cannot work_ with the ChinhDo library's method of managing files (there's no way a background thread will ever be able to force a foreground thread to unlock files), it probably makes the most sense to disable these timeouts completely if we can do that. If the timeout is longer but still active, that would help but would leave the crash in place for longer transactions.

**Comment by HebaruSan** [comment]
We're already using the maximum timeout! :sob: 

https://github.com/KSP-CKAN/CKAN/blob/068a8dd70b66499841c4f2b32facecf7464046fc/Core/CkanTransaction.cs#L19

**Comment by HebaruSan** [comment]
There was some discussion of addressing this in dotnet/runtime#1418, but it hasn't been done yet, and I'm not sure whether that issue is about .NET Framework or just Core.
