### ISSUE TITLE
`System.ArgumentException: The path is not of a legal form` at startup on Windows with incomplete legacy data in registry

### ISSUE THREAD

**Issue by Finn900mc** [KSP-CKAN/CKAN#3495]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.2

No modifications have been made to the GameData folder

Problem
-------
Upon first time start up, a command window appears and displays code below. After about 4 seconds it closes. No other event takes place.

```
Unhandled Exception: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at CKAN.GameInstance..ctor(IGame game, String gameDir, String name, IUser user, Boolean scan)
   at CKAN.GameInstanceManager.LoadInstances()
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by DasSkelett** [comment]
Can you share the contents of the file at `C:\Users\<your_user>\AppData\Local\CKAN\config.json`?
Make sure to cut out the `AuthTokens` section if you have configured any.

**Comment by Finn900mc** [comment]
''
{
  "AutoStartInstance": "",
  "DownloadCacheDir": "C:\\Users\\Finn900\\AppData\\Local\\CKAN\\downloads",
  "CacheSizeLimit": null,
  "RefreshRate": 0,
  "Language": null,
  "GameInstances": [
    {
      "Name": "",
      "Path": "",
      "Game": ""
    }
  ],
  "AuthTokens": {}
}
''

**Comment by HebaruSan** [comment]
Well, the empty `Path` would explain that. How it got like that is another question.

```
$ csharp
Mono C# Shell, type "help;" for help

Enter statements below.
csharp> System.IO.Path.GetFullPath(""); 
System.ArgumentException: The specified path is not of a legal form (empty).
  at System.IO.Path.InsecureGetFullPath (System.String path) [0x00025] in <85ce94efa4ba468a921bc3ed4ecd0dbe>:0 
  at System.IO.Path.GetFullPath (System.String path) [0x00000] in <85ce94efa4ba468a921bc3ed4ecd0dbe>:0 
  at <InteractiveExpressionClass>.Host (System.Object& $retval) [0x00000] in <2fb1043d56014f58b928564c703ee80c>:0 
  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x00038] in <599fbc22e63e4e1d856e79d88570d37f>:0 
  at Mono.CSharpShell.Evaluate (System.String input) [0x00000] in <12eea02d66a84e0bb0d0aaefd91b0b11>:0 
```

If you delete that `config.json` and try again, it might work better.

**Comment by Finn900mc** [comment]
Sadly, it does the same thing and recreates the same confg.json.

**Comment by HebaruSan** [comment]
Are there keys in your registry under `HKEY_CURRENT_USER\Software\CKAN`? If you're not familiar with the registry, you can check this via `regedit`.

**Comment by Finn900mc** [comment]
yes there are. 
(Default)
DownloadCacheDir
KSPAutoStartInstance
KSPBuilds
KSPInstanceCount

**Comment by HebaruSan** [comment]
Aha! Delete them! They get migrated into the `config.json` file when it's absent. You probably have a `KSPInstanceCount` that's greater than 0 but no instances, that would explain how the `Path` ends up empty.

**Comment by Finn900mc** [comment]
Oh my gosh, thank you so much. I deleted them and deleted the config.json before starting it seems to work now. Defiantly wouldn't have been able to do this without help as I didn't know about the registry and was looking for the config in roaming rather than local so thanks truly.
