### ISSUE TITLE
NET framework saying temp file being used by another process

### ISSUE THREAD

**Issue by ohthebiomesyoullgoooooooo** [KSP-CKAN/CKAN#3546]
Background
----------
* Operating System: Windows 10
* CKAN Version: Hubble
* KSP Version: 1.12.0

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I had to move all my mods onto my desktop to install Galaxies unbound, but this has been happening for months now.

Problem
-------
**Describe the bug**
The net framwork thinks it the temp file is being used by another process, and i tried to close all programs running but ckan, same error sometimes, or i just need a new NET install,,

You cannot do anything on ckan if the error shows up.

**Steps to reproduce**
* Go to CKAN and wait
* Click on nothing
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.ManageMods.MarkAllUpdates()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ohthebiomesyoullgoooooooo** [comment]
Wait, it's a false alarm. I keep forgetting to close all programs

**Comment by ohthebiomesyoullgoooooooo** [comment]
However, the error keeps happening most of my time on CKAN.

**Comment by ohthebiomesyoullgoooooooo** [comment]
I'll get the error code.

**Comment by ohthebiomesyoullgoooooooo** [comment]
False alarm.
