### ISSUE TITLE
Could not load file or assembly System.EnterpriseServices, The file or directory is corrupted and unreadable

### ISSUE THREAD

**Issue by ImYesSir** [KSP-CKAN/CKAN#3590]
Background
----------
* Operating System: Windows 11
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Just reinstalled the game, short answer no

Problem
-------
**Describe the bug**
When I try to initialize CKAN and select BuildID64 I get the error ```Could not load file or assembly 'System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)``` and CKAN doesn't initialize it takes me back to select BuildID64

**Steps to reproduce**
* Initialize CKAN
* Select new instance of KSP
* Select BuildID64

**Expected behavior**
When selecting BuildID64 it shows up the error and takes me back to step 2

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/107643905/174137520-ca93949c-f49c-42e6-ac12-d292d405d940.png)

**CKAN error code :**
0x80070570

**Comment by HebaruSan** [comment]
Sounds like a file on your disk may be corrupted and unreadable. Since CKAN doesn't actually do anything with `System.EnterpriseServices`, it's hard to think of something to suggest. Is your game instance in a weird location, like maybe a network share?

**Comment by ImYesSir** [comment]
It's on my NVMe SSD this is the path F:\SteamLibrary\steamapps\common\Kerbal Space Program

**Comment by ImYesSir** [comment]
I mannage to enable the log of ckan and this is what I got ```Unhandled exception:
System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)
File name: 'System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Transactions.Transaction.get_EnterpriseServicesOk()
   at System.Transactions.Transaction.FastGetTransaction(TransactionScope currentScope, ContextData contextData, Transaction& contextTransaction)
   at System.Transactions.Transaction.get_Current()
   at ChinhDo.Transactions.FileManager.TxFileManager.IsInTransaction()
   at ChinhDo.Transactions.FileManager.TxFileManager.CreateDirectory(String path)
   at CKAN.GameInstance.SetupCkanDirectories(Boolean scan)
   at CKAN.GameInstance..ctor(IGame game, String gameDir, String name, IUser user, Boolean scan)
   at CKAN.GameInstanceManager.FindAndRegisterDefaultInstance()
   at CKAN.GameInstanceManager._GetPreferredInstance()
   at CKAN.GameInstanceManager.GetPreferredInstance()
   at CKAN.Main..ctor(String[] cmdlineArgs, GameInstanceManager mgr, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, GameInstanceManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, GameInstanceManager manager)
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
Pre-bind state information
LOG: DisplayName = System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/
LOG: Initial PrivatePath = NULL
Calling assembly : System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Binding succeeds. Returns assembly from C:\Windows\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll.
LOG: Assembly is loaded in default load context.```

**Comment by HebaruSan** [comment]
Thanks, that says the same thing, `System.EnterpriseServices [...] is corrupted and unreadable`. CKAN can't fix that, so you'll have to figure out how to repair your OS. Reinstalling the various .NET Framework packages is one possibility, but if you're not a computer expert, starting over with a new installation of Windows might be easier.
