### ISSUE TITLE
This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms

### ISSUE THREAD

**Issue by lakjsdf48** [KSP-CKAN/CKAN#3681]
Background
----------
* Operating System: Windows 11
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173

**Tried manually installing mods at one point, deleted, and later reinstalled game**

Problem
-------
When attempting to apply changes, CKAN briefly shows an error message then crashes.

**Steps to reproduce**
* Check any mod
* Click on "Apply changes"
* Continue through confirm dialogues
* See error when mods are supposed to download

**Expected behavior**
Mods would download

**Screenshots (if applicable)**

**CKAN error code (if applicable):**
Error is longer with either multiple mods or different mod this message I got from DogeCoin flag mod*
```
Unhandled exception:
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA256Managed..ctor()
   at CKAN.NetFileCache.GetFileHashSha256(String filePath)
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   at CKAN.NetAsyncDownloader.NetAsyncDownloaderDownloadPart.<ResetAgent>b__20_1(Object sender, AsyncCompletedEventArgs args)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

**Comment by HebaruSan** [comment]
Based on a web search for that error message, it looks like you've got some kind of optional Windows security policy applied, see here for background and hopefully how to disable it:

- https://learn.microsoft.com/en-us/answers/questions/211279/sharepoint-2016-configuration-failed-this-implemen.html
- https://learn.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/federal-information-processing-standard-security-standards
- https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashing-and-signing

**Comment by lakjsdf48** [comment]
I've learned about the optional security measure but I have found no way to disable it. (I don't posses much computer knowledge) so the few methods don't seem to work. any ideas?

**Comment by HebaruSan** [comment]
Does this help?

https://docs.trendmicro.com/all/ent/sc/v3.0/en-US/cmcolh/t_fips.html#:~:text=In%20Security%20Settings%2C%20expand%20Local,signing%2C%20and%20then%20click%20Disabled.

**Comment by lakjsdf48** [comment]
it doesn't seem to because it is a different software (and , or) I don't have access to administrative tools.

**Comment by HebaruSan** [comment]
Hmm, if you don't have access to administrator tools, then you probably won't be able to fix the problem. Either way there's not much more the CKAN team can do to help other than trying to point you toward the cause of the problem.

**Comment by lakjsdf48** [comment]
Wait a minute, I think I found it I might be able to fix it

**Comment by HebaruSan** [comment]
I assume you stopped responding because you fixed it, so this is now safe to close.
