### ISSUE TITLE
[Bug] Unable to uninstall all mods with uninstall all checkmark

### ISSUE THREAD

**Issue by glowingc4** [KSP-CKAN/CKAN#3714]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.32.2
* KSP Version: 1.12.0

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Nope.

Problem
-------
**Describe the bug**
For some reason I couldn't load into KSP so I wanted to uninstall all my mods quickly, but it showed up with Object cannot something and I tried a few times, when I did apply changes it came up with the error message, and the cmd-line is not responding rn.

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
Unhandled exception:
System.InvalidOperationException: Form that is already displayed modally cannot be displayed as a modal dialog box. Close the form before calling showDialog.
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at CKAN.GUI.YesNoDialog.<>c__DisplayClass1_0.<ShowYesNoDialog>b__0()
   at CKAN.GUI.YesNoDialog.ShowYesNoDialog(Form parentForm, String text, String yesText, String noText)
   at CKAN.GUI.Main.YesNoDialog(String text, String yesText, String noText)
   at CKAN.GUI.ManageMods.AllowClose()
   at CKAN.GUI.Main.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by glowingc4** [comment]
update, if you actually try to apply changes the object thing happens, and then it works but then when you try to do it again, it shows it again and if you click quit it shows the error
