### ISSUE TITLE
[Bug] CKAN giving error message and not loading.

### ISSUE THREAD

**Issue by BostonBlack** [KSP-CKAN/CKAN#3754]
Background
----------
* Operating System: 

Edition	Windows 11 Home
Version	22H2
Installed on	‎22/‎05/‎2022
OS build	22623.1037
Experience	Windows Feature Experience Pack 1000.22638.1000.0

* CKAN Version: 

v1.31.2 Juno

* KSP Version: 

1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

no

Problem
-------
**Describe the bug**

CKAN gives error report and will not open when run

**Steps to reproduce**

crash computer (HYPERVISOR_ERROR) while installing mods
try to run CKAN after restarting

**Expected behavior**

CKAN to open and load

**CKAN error code (if applicable):**

```
Unhandled exception:
System.TypeInitializationException: The type initializer for 'CKAN.Versioning.GameVersion' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GameVersionProviders.KspBuildMap.get_KnownVersions()
   at CKAN.Versioning.GameVersion..cctor()
   --- End of inner exception stack trace ---
   at CKAN.Versioning.GameVersion.op_Equality(GameVersion v1, GameVersion v2)
   at CKAN.GameInstance.Version()
   at CKAN.GameInstance.get_Valid()
   at CKAN.GameInstance..ctor(IGame game, String gameDir, String name, IUser user, Boolean scan)
   at CKAN.GameInstanceManager.FindAndRegisterDefaultInstance()
   at CKAN.GameInstanceManager._GetPreferredInstance()
   at CKAN.GameInstanceManager.GetPreferredInstance()
   at CKAN.GUI.Main..ctor(String[] cmdlineArgs, GameInstanceManager mgr, Boolean showConsole)
   at CKAN.GUI.GUI.Main_(String[] args, GameInstanceManager manager, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Gui(GameInstanceManager manager, GuiOptions options, String[] args)
   at CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, GameInstanceManager manager)
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args) 
```

**Comment by HebaruSan** [comment]
This was fixed in #3733.
