### ISSUE TITLE
Unhandled Exception due to not being apart of the Windows Platform FIPS validated cryptographic algorithms.

### ISSUE THREAD

**Issue by Gryffen1971** [KSP-CKAN/CKAN#3773]
Background
----------
* Operating System:   Win 11 Pro
* CKAN Version:  Latest Version
* KSP Version:  Latest Version

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
CKan throws a "Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."

**Steps to reproduce**
* Go to...  Have "SHA-1 and SHA-256" Enabled in Bios.
* Click on...  Install or Update Mod
* See error...  See Error Code Section

**Expected behavior**
To work! (Sarchasm

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
Unhandled exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA256Managed..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateI
![ScreenShot_20230212113323](https://user-images.githubusercontent.com/10908465/218323959-7acdb83d-5aad-48c2-a8f3-038b49d2b0f0.png)
![image_2023-02-12_113428399](https://user-images.githubusercontent.com/10908465/218323964-03549ba4-4a64-4281-91a7-6cf624ac173f.png)
nstance[T]()
   at CKAN.NetFileCache.GetFileHash[T](String filePath, String hashSuffix, Dictionary`2 cache, IProgress`1 progress)
   at CKAN.NetFileCache.GetFileHashSha256(String filePath, IProgress`1 progress)
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error, Boolean canceled, String etag)
   at CKAN.NetAsyncDownloader.<>c__DisplayClass20_0.<DownloadModule>b__1(Object sender, AsyncCompletedEventArgs args, String etag)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at CKAN.ResumingWebClient.OnOpenReadCompleted(OpenReadCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
   
```

**Comment by HebaruSan** [comment]
Reading #1850, we might be able to suppress this message by switching from `SHA256Managed` to `SHA256CryptoServiceProvider`.

https://github.com/KSP-CKAN/CKAN/blob/98f2836a5c144b9e5e73b6ee5c854c178ad80e4b/Core/Net/NetFileCache.cs#L713-L714

**Comment by Gryffen1971** [comment]
Even when I Dismiss the Message the Program Crashes.
Also, sorry for the Image being within the Error Code. I posted it improperly!

**Comment by HebaruSan** [comment]
FIPS can be turned off if you want to try that in the meantime before a code change is released:

- https://learn.microsoft.com/en-us/answers/questions/211279/sharepoint-2016-configuration-failed-this-implemen.html
- https://learn.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/federal-information-processing-standard-security-standards
- https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashing-and-signing
- https://docs.trendmicro.com/all/ent/sc/v3.0/en-US/cmcolh/t_fips.html

(Previously saw this in #3681 but only now did a historical issue search for "FIPS" and to find #1497 and #1850.)

**Comment by Gryffen1971** [comment]
I disabled it and will try it out.
Will post when done.

**Comment by Gryffen1971** [comment]
I installed 3 Mods and CKan ran correctly with No Errors. So, I will leave the setting off when I use Ckan until there is a Fix for it.

Thanks @HebaruSan For the Docs so, I could find where in Windows to turn FIPS Off.
