### ISSUE TITLE
[Bug] NRE thrown on purge all cache files

### ISSUE THREAD

**Issue by GreenKeldeo** [KSP-CKAN/CKAN#3809]
Background
----------
* Operating System: Windows 11 Home 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
* CKAN Version: 1.31.1
* KSP Version: 1.12.5 (Although I don't think it matters here)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes, but not to the CKAN cache - nor do I have the CKAN cache open elsewhere.

Problem
-------
**Describe the bug**
With a 12.8gb CKAN cache, purge all throws an NRE.

**Steps to reproduce**
* Open CKAN
* Go to CKAN settings
* Press purge
* Select purge all

**Expected behavior**
Cache files are purged

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/37720445/224503690-10e4d16e-c0e5-4a4d-9ffb-5930abac0160.png)

**CKAN error code (if applicable):** N/A; Exception text can be found below:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GUI.Contents._UpdateModContentsTree(CkanModule module, Boolean force)
   at CKAN.GUI.SettingsDialog.PurgeAllMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment]
This should be an easy one. `PurgeAllMenuItem_Click` passes `null`:

https://github.com/KSP-CKAN/CKAN/blob/efb7fc8f56eb2c265e930719005ae01f4c1ac9bb/GUI/Dialogs/SettingsDialog.cs#L266-L267

and `_UpdateModContentsTree` tries to access a property on it:

https://github.com/KSP-CKAN/CKAN/blob/efb7fc8f56eb2c265e930719005ae01f4c1ac9bb/GUI/Controls/ModInfoTabs/Contents.cs#L58-L71
