### ISSUE TITLE
[Bug]: Empty path name is not legal with no default game instance

### ISSUE THREAD

**Issue by LunarHackett003** [KSP-CKAN/CKAN#3862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.33.0

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No manual changes to the game folder made

### Describe the bug

Recently updated to the newest CKAN build via the auto-updater. 
Upon attempting to select a game instance or exit the program, I am greeted with the error message below

![image](https://github.com/KSP-CKAN/CKAN/assets/61294652/512b2f0d-0e86-4263-bea9-ef33df698c92)
"Empty path name is not legal"

Followed by the exception information
```Unhandled exception:
System.ArgumentException: Empty path name is not legal.
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at CKAN.GUI.GUIConfiguration.SaveConfiguration(GUIConfiguration configuration)
   at CKAN.GUI.Main.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

* Have multiple instances and no default instance
* Open CKAN
* Select Game Instance
* Observe "file path not legal" error and click continue.
* Use CKAN as normal.
* Attempt to launch game, observe error yet again.
* Attempt to close CKAN, observe error

### Relevant log output

```shell
Unhandled exception:
System.ArgumentException: Empty path name is not legal.
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at CKAN.GUI.GUIConfiguration.SaveConfiguration(GUIConfiguration configuration)
   at CKAN.GUI.Main.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment]
Thanks for the report. There is a workaround: Check the "Set as default" checkbox in Manage Game Instances, then restart CKAN.

**Comment by Kronosiesium** [comment]
happens to me as well, has never happened before 1.33
