### ISSUE TITLE
[Bug]: Access to the path CdFileMgr denied.

### ISSUE THREAD

**Issue by ADWadmin** [KSP-CKAN/CKAN#3963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 Pro 22H2 19045.3693

### CKAN Version

1.34.2

### Games

KSP 1

### Game Version

1.12.5.03190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

After a long hiatus, I decided to get back in the game. Started CKAN to update the installed modifications and got the above error.

I've tried specifying an alternate path for "Download Cache" in the settings. However, this did not make any difference, CKAN still tries to access the path "..\Temp\CdFileMgr\" . (The setting applies. I see the new path in config.json).

I checked the permissions of the directory "..\CdFileMgr" my user has full access. 

I tried deleting the "..\CdFileMgr" directory. When CKAN starts, it is successfully created and the .tmp file appears in it, but the error persists. 

I also tried running CKAN as administrator (in PS run .\ckan.exe --asroot). Error persists.

![image](https://github.com/KSP-CKAN/CKAN/assets/48478709/7b4c717d-e5df-4ab5-92b5-436d28050c16)

### Steps to reproduce

Run CKAN and wait for the repositories to be updated.

### Relevant log output

Scanning for DLCs and manually installed modules...
Loading cached repository data
Updating repositories...
Refreshing game version data
Downloading "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz"
Loading modules from downloaded default repository...
Access to the path 'C:\Users\ADWadmin\AppData\Local\Temp\CdFileMgr\9fbc14b9-805e-47.tmp' is denied.
Failed to roll back.
Repository update failed!

**Comment by HebaruSan** [comment]
Hi @ADWadmin, thanks for reporting this. To investigate it, we'll need to pinpoint which operation is failing on your PC, and the default messages don't have enough information to do that. Please follow these steps if you're willing:

1. Download this test build and unzip `ckan.exe` from it to any folder: [ckan.zip](https://github.com/KSP-CKAN/CKAN/files/13850836/ckan.zip)
   This is a special build of CKAN with additional logging around the spot where this error occurs, which will tell us whether it's failing to read from the file or failing to delete it.
2. Download and unzip this logging config file to the same folder: [log4net.zip](https://github.com/KSP-CKAN/CKAN/files/13850849/log4net.zip)
   This enables those log messages and directs logging into a CKAN.log file.
3. Run the test build
4. Refresh in CKAN and get the error
5. A CKAN.log file should be created. Please share it here.

Thanks!

**Comment by ADWadmin** [comment]
Greetings! 


I'm attaching the log: [CKAN.log](https://github.com/KSP-CKAN/CKAN/files/13918913/CKAN.log)

**Comment by HebaruSan** [comment]
Thanks! It looks like your system is stopping CKAN from **deleting** the file:

```
 51127 INFO  CKAN.RepositoryDataManager  Loading C:\Users\ADWadmin\AppData\Local\Temp\CdFileMgr\56e0f696-8839-45.tmp...
 54212 DEBUG CKAN.RepositoryDataManager  Saving data for default repo...
 55638 DEBUG CKAN.RepositoryDataManager  Deleting C:\Users\ADWadmin\AppData\Local\Temp\CdFileMgr\56e0f696-8839-45.tmp...
 55645 ERROR CKAN.RepositoryDataManager  Repository update failed
System.UnauthorizedAccessException: Access to the path 'C:\Users\ADWadmin\AppData\Local\Temp\CdFileMgr\56e0f696-8839-45.tmp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.RepositoryDataManager.Update(Repository[] repos, IGame game, Boolean skipETags, NetAsyncDownloader downloader, IUser user)
```

That's pretty wild. Not only should temp files pretty much never be impossible to delete, but it's allowing CKAN to _create_ and _read_ the file without issues. I'd recommend checking the permissions on the `C:\Users\ADWadmin\AppData\Local\Temp\` directory (and the `CdFileMgr` subfolder if it still exists) to see if you can figure out why that's happening. Maybe you ran CKAN as another user (possibly an admin?) at some point and _that_ user owns `CdFileMgr`?

**Comment by HebaruSan** [comment]
We had a user on Discord report this, and in their case, the cause was some anti-virus software holding the downloaded file in quarantine. Maybe that's the same for you?

**Comment by ADWadmin** [comment]
Oh, I solved the problem, but I'm not sure what the solution was.
What I did: 

 * Uninstalled KSP and SKAN.
 * Cleared all related files in the AppData directory (save files, cache files, configuration files, etc.).
 * I used "Auslogics BoostSpeed" (Registry Cleaner and Deep Disk Cleaner).
 * Checked for Windows updates and installed them.
 * Reboot.
 * Installed KSP.
 * Put skan.exe in the game directory.
 * I added scan.exe to my antivirus exclusions.
 * I added the "%AppData%\Local\Temp\CdFileMgr\" directory to my antivirus exclusions.

After that, the SKAN works without errors.

**Comment by MemetonCMemeton** [comment]
as someone who has bitdefender as well it is indeed what was causing this i fixed it by putting ckan.exe and the ksp folder in exceptions
