### ISSUE TITLE
Opening the relationships tab with locally-installed .ckan files throws an exception

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4005]
```
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Module not found: TweakScaleRescaled 
   at CKAN.Registry.getAvail(String identifier)
   at CKAN.Registry.AvailableByIdentifier(String identifier)
   at CKAN.IRegistryQuerierHelpers.CompatibleGameVersions(IRegistryQuerier querier, IGame game, String identifier)
   at CKAN.GUI.Relationships.indexedNode(IRegistryQuerier registry, CkanModule module, RelationshipType relationship, RelationshipDescriptor relDescr, GameVersionCriteria crit)
   at CKAN.GUI.Relationships.findDependencyShallow(IRegistryQuerier registry, RelationshipDescriptor relDescr, RelationshipType relationship, GameVersionCriteria crit)
   at CKAN.GUI.Relationships.<>c__DisplayClass20_1.<ForwardRelationships>b__2(RelationshipDescriptor dependency)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CKAN.GUI.Relationships.AddChildren(IRegistryQuerier registry, TreeNode node)
   at CKAN.GUI.Relationships._UpdateModDependencyGraph(CkanModule module)
   at CKAN.GUI.Relationships.set_SelectedModule(GUIMod value)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by HebaruSan** [comment]
I assume you clicked the row for a mod that depends on that mod?

**Comment by JonnyOThan** [comment]
> I assume you clicked the row for a mod that depends on that mod?

Or that mod itself, yes.
