### ISSUE TITLE
[Bug]: NRE in MarkAllUpdates

### ISSUE THREAD

**Issue by miro60559** [KSP-CKAN/CKAN#4053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 11

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no.

### Describe the bug

mods are not displayed at all. a window with text pops up:
Unhandled exception has occurred in your application. if you click Continue. the appľication will 
ignore this error and attempt to continue.if you click Quit, the application will dose immediately. 
Object reference not set to an instance of an object
<img width="330" alt="ckan error" src="https://github.com/KSP-CKAN/CKAN/assets/162689358/1c6eeb6e-53ba-405d-a5af-36d743f2ade5">

### Steps to reproduce

the error repeats every time you run it

### Relevant log output

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.GUI.ManageMods.MarkAllUpdates()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment]
I think `mainModList.full_list_of_mod_rows` the thing that's null:

https://github.com/KSP-CKAN/CKAN/blob/351bd9449177c44c65ccc305b91bd19e6fb8a8f1/GUI/Controls/ManageMods.cs#L503
