### ISSUE TITLE
ConsoleUI should check for conflicts between chosen recommendations and suggestions, plus a crash

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4072]
If you try to install RP-1 with the console UI, you get several "suggested mod" windows that you don't see when doing the same process on windows.  This can lead to failed installs because it allows you to select conflicting suggested mods:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/1594c4fe-d36b-4688-892d-30525328e3e3)

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/853a783e-fe4d-40d4-abb4-4c6112346d71)

In that final recommend/suggest screen, when I did ctrl-A to select all of them, it crashed the dev build:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.             │
   at CKAN.RelationshipResolver.AddModulesToInstall(CkanModule[] modules)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, RegistryManager registry_manager, HashSet`1& possibleConfigOnlyDirs, IDownloader downloader, Boolean ConfirmPrompt)
   at CKAN.ConsoleUI.InstallScreen.Run(ConsoleTheme theme, Action`1 process)
   at CKAN.ConsoleUI.ModListScreen.ApplyChanges(ConsoleTheme theme)
   at CKAN.ConsoleUI.ModListScreen.<>c__DisplayClass0_0.<.ctor>b__27(Object sender, ConsoleTheme theme)
   at CKAN.ConsoleUI.Toolkit.ScreenContainer.Interact(ConsoleTheme theme)
   at CKAN.ConsoleUI.Toolkit.ScreenContainer.Run(ConsoleTheme theme, Action`1 process)
   at CKAN.ConsoleUI.ConsoleCKAN..ctor(GameInstanceManager mgr, String themeName, Boolean debug)
   at CKAN.ConsoleUI.ConsoleUI.Main_(GameInstanceManager manager, String themeName, Boolean debug)
   at CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, GameInstanceManager manager)
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
@JonnyOThan, why does the title mention `suppress_recommendations`? This seems to just be noting that ConsoleUI is more aggressive about presenting recommendations-of-accepted-recommendations than GUI is, along the lines of #4031. If there's a connection to `suppress_recommendations`, can you please describe it in the problem description?

**Comment by HebaruSan** [comment]
I'm also assuming that in the crash related to <kbd>Ctrl+A</kbd>, you also pressed <kbd>F9</kbd> after that, since all <kbd>Ctrl+A</kbd> does is add some `CkanModule`s to a `HashSet`.

**Comment by JonnyOThan** [comment]
>  why does the title mention suppress_recommendations

Ah sorry, that was an assumption based on the fact that RP-1 uses that property extensively.

> I'm also assuming that in the crash related to Ctrl+A, you also pressed F9 after that, since all Ctrl+A does is add some CkanModules to a HashSet, and that stack trace shows the installation moving along to the step after recommendations.

Correct - sorry for not including that; the crash occurred after pressing Ctrl-A and then F9.
