### ISSUE TITLE
No window to ask for auto-updating - Null Reference Exception - Mono Develop - Ubuntu 64

### ISSUE THREAD

**Issue by sparkybear** [KSP-CKAN/CKAN#785]
System.NullReferenceException: Object reference not set to an instance of an object
  at CKAN.Main.Main_Load (System.Object sender, System.EventArgs e) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.OnLoad (System.EventArgs e) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) [0x00000] in <filename unknown>:0 

Restarting Mono helped for the first instance, but it continues to pop up intermittently. May be an issue with Mono.

**Comment by AlexanderDzhoganov** [comment]
Hey, can you delete your KSP/CKAN/GUIConfig.xml and try again?

**Comment by sparkybear** [comment]
I did so, and it hasn't happened since. I will let you know if it comes up again.

**Comment by AlexanderDzhoganov** [comment]
Thanks, closing issue for now.

**Comment by sparkybear** [comment]
Getting similar errors on a Windows even after resetting the GUIConfig.xml. Gone through the normal trouble shooting stages of re-downloading, resetting the KSP installation, re-installing .NET frameworks. Resetting the CKAN folder did work and it will open without any issues, but very few (10 out of 70) of the mods that were installed through CKAN are shown on the list (I'm assuming that's expected behavior after deleting the CKAN folder). Nothing out of the ordinary happened prior to the error.  

System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.RegistryManager.AscertainDefaultRepo()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main._UpdateModsList()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
