### ISSUE TITLE
Crash due to lack of temporary files.

### ISSUE THREAD

**Issue by Antsiscool** [KSP-CKAN/CKAN#801]
When installing mods on a windows computer, if there are more than 65535 temporary files, ckan will throw an exception with the text "the file exists.". This is a shared limit for all programs on the computer. would it be possible to use a custom temporary directory for downloads, or warn the user with a more specific error message if no temporary files can be created.

```
System.IO.IOException was unhandled by user code
  HResult=-2147024816
  Message=The file exists.

  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
       at CKAN.NetAsyncDownloader.NetAsyncDownloaderDownloadPart..ctor(Uri url, Int64 expectedSize, String path) in c:\Users\Ants\Documents\CKAN\CKAN-core\Net\NetAsyncDownloader.cs:line 40
       at CKAN.NetAsyncDownloader.<Download>b__0(KeyValuePair`2 url) in c:\Users\Ants\Documents\CKAN\CKAN-core\Net\NetAsyncDownloader.cs:line 81
       at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
       at CKAN.NetAsyncDownloader.Download(ICollection`1 urls) in c:\Users\Ants\Documents\CKAN\CKAN-core\Net\NetAsyncDownloader.cs:line 81
       at CKAN.NetAsyncDownloader.DownloadModules(NetFileCache cache, IEnumerable`1 modules) in c:\Users\Ants\Documents\CKAN\CKAN-core\Net\NetAsyncDownloader.cs:line 148
       at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, NetAsyncDownloader downloader) in c:\Users\Ants\Documents\CKAN\CKAN-core\ModuleInstaller.cs:line 215
       at CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOptions options, NetAsyncDownloader downloader) in c:\Users\Ants\Documents\CKAN\CKAN-core\ModuleInstaller.cs:line 158
       at CKAN.Main.InstallList(HashSet`1 toInstall, RelationshipResolverOptions options, NetAsyncDownloader downloader) in c:\Users\Ants\Documents\CKAN\CKAN-GUI\MainInstall.cs:line 280
       at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e) in c:\Users\Ants\Documents\CKAN\CKAN-GUI\MainInstall.cs:line 228
       at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
  InnerException: 

```

**Comment by pjf** [comment]
Oh my! I've never even heard of this before. Since this is something that's likely to affect the user for many operations (not just the CKAN) I imagine our best option here is to inform the user that their temp files allocation is full.

Thank you so much for your report!

~ Paul

**Comment by FireFaced** [comment]
So, I accidentally reclosed #1367 .
I'm just going to post here since it's actually on topic: Clearing the temp file works..... to an extent. I noticed later that it complained about a DIFFERENT temp file. This is driving me insane

**Comment by embix** [comment]
This bug is very annoying. How about choosing another temp file naming algorithm? GUID seems like a good fit.

**Comment by HebaruSan** [comment]
We don't download mods to temporary files anymore as of #3666; instead the target file for `NetAsyncDownloader` is in the `downloading` subfolder of the cache, so interrupted downloads can be resumed. Closing as fixed.
