### ISSUE TITLE
Unhandled Exception when Clicking Relationships tab

### ISSUE THREAD

**Issue by arcwolf** [KSP-CKAN/CKAN#822]
Error below, fresh install CKAN no mods installed. Fresh install of KSP 1.0

Just poking around in the interface since I've never used it before, clicked Relationships Tab and bam...

CKAN v1.6.11-0-g0000000(beta) - KSP 1.0.0

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: node
   at System.Windows.Forms.TreeNodeCollection.AddInternal(TreeNode node, Int32 delta)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Dazpoet** [comment]
Which mod did you have selected when this happened? Can you reproduce the problem and provide reproduction steps? What OS are you running?

**Comment by arcwolf** [comment]
Windows 8.1  64x, no mods installed. Fresh install of KSP 1.0

Reproducible every time, simply open the program and click relationships results in NPE. Pretty simple steps.
