### ISSUE TITLE
CKAN GUI crashes on cancelled download

### ISSUE THREAD

**Issue by obi1kenobi** [KSP-CKAN/CKAN#848]
Expected result:
- The CKAN GUI should return to the "Manage mods" tab.

Actual result:
- CKAN crashes.

Setup: Win7 x64, .NET 4.0, CKAN v1.6.13

Repro:
1. select any mod (preferably a larger one), click "Go to changes" and start installing it
2. click the "Cancel" button as soon as it appears, and before the mod has finished downloading
3. observe CKAN pop up an error window, freeze and then crash entirely

Exception text:
```
CKAN.CancelledActionKraken: Download cancelled by user
   at CKAN.NetAsyncDownloader.DownloadModules(NetFileCache cache, IEnumerable`1 modules)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, NetAsyncDownloader netAsyncDownloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

I expect this should be rather simple to fix, as the CKAN GUI already recognizes that the download was interrupted, and simply fails to catch the background worker's exception.

**Comment by obi1kenobi** [comment]
What I expect is a related error happens when attempting to download mods with no Internet connection.

Expected result:
- There is no Internet connection, so the GUI should display an error and then return to the "Manage mods" tab.

Actual result:
- CKAN crashes.

Repro:
1. disable your Internet connection
2. select and attempt to install any mod
3. observe CKAN pop up an error window and then crash.

Exception text:
Uh oh, the following things went wrong when downloading...

```
System.Net.WebException: The remote name could not be resolved: 'github.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
System.Net.WebException: The remote name could not be resolved: 'github.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
System.Net.WebException: The remote name could not be resolved: 'kerbalstuff.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
```

**Comment by mgsdk** [comment]
It seems this is related to the netcode for Windows. I can't replicate any of the issues on Linux. I would expect OS X is in the clear as well, since this also relies on libcurl for downloads.

**Comment by Postremus** [comment]
@obi1kenobi  does the gui still crash after cancelling downloads in 1.10.0?

**Comment by obi1kenobi** [comment]
Not any more, thanks for fixing the problem!
