### ISSUE TITLE
Unhanded exception when updating Firespitter

### ISSUE THREAD

**Issue by t3hk0d3** [KSP-CKAN/CKAN#859]
```
CKAN.FileExistsKraken: Trying to write D:/SteamGames/SteamApps/common/Kerbal Space Program/GameData/Firespitter/Resources/Firespitter.cfg but it already exists.
   at CKAN.ModuleInstaller.CopyZipEntry(ZipFile zipfile, ZipEntry entry, String fullPath, Boolean makeDirs)
   at CKAN.ModuleInstaller.InstallModule(CkanModule module, String zip_filename)
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, NetAsyncDownloader netAsyncDownloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

I've removed Firespitter completely, but it didn't help.

**Comment by t3hk0d3** [comment]
Seems like updating Firespitter and Firespitter Core at same time is bad idea.

**Comment by t3hk0d3** [comment]
Just updating Firespitter alone cause:
```
The following inconsistencies were found:
Firespitter wishes to install GameData/Firespitter/Resources/Firespitter.cfg, but this file is registered to KerbalAircraftExpansion   at CKAN.Registry.RegisterModule(Module mod, IEnumerable`1 absolute_files, KSP ksp)
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, NetAsyncDownloader netAsyncDownloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by t3hk0d3** [comment]
Removing both Firespitter and Firespitter Core and all dependent mods, than installing Firespitter works fine.

But on installing Kerbal Aircraft Extension happens this:

```


Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : KerbalAircraftExpansion v2.4.1
Owning Mod     : Firespitter
CKAN Version   : v1.6.16-0-g0000000 (beta)

Your GameData has been returned to its original state.
```

**Comment by Dazpoet** [comment]
Yes KAX and Firespitter in the same install causes issues. How did you manage to install both? Should be impossible :o 

See https://github.com/KSP-CKAN/NetKAN/pull/1217

**Comment by t3hk0d3** [comment]
@Dazpoet I've managed to do that on 0.91

**Comment by mgsdk** [comment]
Should be fixed now via https://github.com/KSP-CKAN/NetKAN/pull/1264?
