### ISSUE TITLE
Unhandled exception when selecting/downloading mod

### ISSUE THREAD

**Issue by Hexicube** [KSP-CKAN/CKAN#864]
I'm trying to install TAC Life Support, and I get the following exception when selecting the mod (also when downloading it, but it's likely the same issue):

```
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, Relationship reason, RelationshipResolverOptions options, Boolean soft_resolve)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options)
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, Relationship reason, RelationshipResolverOptions options, Boolean soft_resolve)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options)
   at CKAN.RelationshipResolver..ctor(ICollection`1 modules, RelationshipResolverOptions options, Registry registry, KSPVersion kspversion)
   at CKAN.MainModList.ComputeChangeSetFromModList(Registry registry, HashSet`1 changeSet, ModuleInstaller installer, KSPVersion version)
   at CKAN.Main.UpdateChangeSetAndConflicts(Registry registry)
   at CKAN.Main.ModList_CellValueChanged(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridViewCell.SetValue(Int32 rowIndex, Object value)
   at System.Windows.Forms.DataGridView.PushFormattedValue(DataGridViewCell& dataGridViewCurrentCell, Object formattedValue, Exception& exception)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewDataErrorContexts context)
   at System.Windows.Forms.DataGridView.NotifyCurrentCellDirty(Boolean dirty)
   at System.Windows.Forms.DataGridViewCheckBoxCell.OnCommonContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I'm using CKAN v1.6.16 on KSP 1.0.2, with a near-fresh install (I manually added RPM with ModuleManager before using CKAN, will try removing those). TAC seems to be the only mod that causes the exception, several other mods do not show the same issue:
- ATM
- Alternate Resource Panel
- Better Buoyancy
- Community Resource Pack
- DangIt!
- Distant Object Enhancement (with config mod)
- KAC
- KAS
- KIS
- Scatterer
- Stage Recovery

**Comment by Hexicube** [comment]
Update: Removing ModuleManager/RPM from my game data doesn't clear it from the installed mod list (still shows as auto-detected). May put that as a separate bug report, since I would expect it to remove the auto-detected mods from the list, as well as try to get me to install ModuleManager.

**Comment by Hexicube** [comment]
Update: TAC installed after checking TACLS Stock Config prior to selecting TACLS. Looking inside the TACLS dependencies, it mentions a TAC realism overhaul mod which CKAN doesn't have listed anywhere, perhaps this is the cause (dependency resolution falls apart there maybe)?

**Comment by Dazpoet** [comment]
See https://github.com/KSP-CKAN/CKAN-GUI/issues/95 and I think you need a `ckan update` to remove AD mods from the list.

**Comment by Hexicube** [comment]
There doesn't appear to be a way to remove AD mods from the GUI version, so really that should be addressed instead of needing people to use a command-line.

I also didn't see your issue because I was unaware that there were separate issues for the GUI version only.

**Comment by Dazpoet** [comment]
pressing refresh in the gui should have the same effect as a `ckan update` and it normally kills of stuff faster than the cli does :s Are you sure there aren't any residual files lurking about?

**Comment by Hexicube** [comment]
Refresh via the GUI had no effect, that was the first thing I tried. There were no residual files (ModuleManager is 1 file, can't exactly fail to remove all of it).

**Comment by pjf** [comment]
New release coming out now which fixes this.
